### ISSUE TITLE
No vehicles in list

### ISSUE THREAD

**Issue by johandenver2** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#1]
When I load an existing save with the mod enabled I get no vehicles in the list at all. I get info about the mod shortcut in the HUD so it seems to be loaded. Also alt+v is also used by Vehicle Explorer which a lot of potential users might be using.

**Comment by Drmattymd** [comment]
Had the same issue and found it was because the workshop hours were closed, changed the time in the settings and list populated

**Comment by johandenver2** [comment]
Unfortunately it must be something else for me. It's still empty even during open hours.

**Comment by MathiasHun** [comment]
> Unfortunately it must be something else for me. It's still empty even during open hours.

If it is not there and in the settings "Repair only in vehicle workshop" set is to On, the vehicle will not appear in the list

Set "Repair only in vehicle workshop" to Off and the vehicle should appear in the list

**Comment by DrewCZ** [comment]
When "Repair only in vehicle workshop" is ON, only the first vehicle in the first workshop is loaded, missing other vehicles, when I have two workshops, or parked more than one vehicle.
![obrazek](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/26751314/e94daf01-1475-44b6-9585-330b48d23449)

**Comment by DrewCZ** [comment]
Interesting. ALL (more than the first one) vehicles in THIS mod repair trigger are loaded correctly. 
https://www.kingmods.net/en/fs22/mods/28345/m18-impact-workshop-trigger

**Comment by MathiasHun** [comment]
> Interesting. ALL (more than the first one) vehicles in THIS mod repair trigger are loaded correctly.

Unfortunately, not all workshops may be compatible with the mod.

I tested with these mods:
Workshop Workbench (DJ WoodZ)
Lizard Repair Ramp (MrHector)

**Comment by MathiasHun** [comment]
> When "Repair only in vehicle workshop" is ON, only the first vehicle in the first workshop is loaded, missing other vehicles, when I have two workshops, or parked more than one vehicle. 

Which workshop is this?

**Comment by DrewCZ** [comment]
https://forbidden-mods.de/filebase/file/28963-ls22-mw-hofpack-part-2/
building #13 workshop with bale shed

the map has already been built in the shop and workshop - the map is here: https://forbidden-mods.de/filebase/file/38687-irgendwo-in-th%C3%BCringen-iii/

also, we use that mentioned tool (see above)

and also tested with default ingame workshop building - see picture above

**Comment by MathiasHun** [comment]
Hi, I'm very sick, but I think I fixed the error. I will share it soon.
