### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by Drmattymd** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#10]
Window randomly pops up saying "The mechanic cannot repair this vehicle, visit RVB Service"
When this occurs it will not let you exit the dialog box. Happened to me three times in a row trying to resume my save. Also saw another report of this on Reddit

**Comment by MathiasHun** [comment]
Hi, I'm sorry. I have not experienced this error before. I'll test it again.
log.txt?

**Comment by Drmattymd** [comment]
So I think its a vehicle breakdown, but there's no warning and I'm unable
to close it out but the game still runs in the background.  When I enter
the vehicle before it happens, in the console log it says
"onEnterVehicleFault: thermostat overHeating".

I'm not sure if it matters or not but when it happened the vehicle was
being operated by courseplay worker.  The last time it happened, after I
restarted the game I did the inspection and am currently waiting on the
repair.

In retrospect, I should have tried operating manually for the same
approximate time to see if it occurred the same way or if it would give any
warning or just breakdown without locking up the screen.

**Comment by AHRichie** [comment]
Hi, I had the same error appearing, and you cant dimiss it. I have tested and found it seems to be related to the Courseplay auto repair setting, the default is set to repair, when CP is used. And the moment CP picked up some wear on the vehicle and tried to repair it, it gives the same dialog as when you try to repair a vehicle in the normal repair station. 

Once i turned this setting to "Do not repair" it worked fine, with both CP and RVB at the same time.

**Comment by astro80** [comment]
same problem for me, disabled the option from CP and the problem still remain.

**Comment by MathiasHun** [comment]
Fixed, will be uploaded soon
