### ISSUE TITLE
FS25 Ein Dieb der dein Mod klaut?!

### ISSUE THREAD

**Issue by Johnny22775** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#103]
Hey, hab ich grad gefunden!

https://www.modland.net/fs25-mods/gameplay/real-vehicle-breakdowns.html  schau es Dir mal an...

**Comment by MathiasHun** [comment]
Hello, thank you for letting me know.

**Comment by bojanh66** [comment]
https://www.kingmods.net/en/fs25/mods/58067/real-vehicle-breakdowns
here also

**Comment by MathiasHun** [comment]
> https://www.kingmods.net/en/fs25/mods/58067/real-vehicle-breakdowns here also
Hello, thank you for letting me know.
I reported it there as well, and it has already been removed.
