### ISSUE TITLE
Temperature indicator not working

### ISSUE THREAD

**Issue by dinogk** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#11]
Hi!... Love this mod, gives much more reality to FS22, thanks for your work. 

I've found an issue since i've added your mod and it's that the temperature indicator on the dashboard isn't showing nothing, it just stays on 0. 

I've experienced this on a mod of a John Deere and Fiat-Allis tractors, a Scania truck, all of them from third party modders, but also it does it in the Volvo F16 from the Platinum Expansion.

Check the screen captures that I append.

![fsScreen_2024_03_14_22_00_22](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/163483193/31ee5dc5-4f61-4dde-9fc9-2ebb82f920ff)
![fsScreen_2024_03_14_22_01_11](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/163483193/879c4a98-d649-4ff4-89df-7c780ef63b51)
![fsScreen_2024_03_14_22_01_23](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/163483193/09b0b457-58cc-4087-881c-a08fd20eaeb3)
![fsScreen_2024_03_14_22_04_57](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/163483193/3d1d6bd5-98d6-45c4-bed5-ca1b7838b9e8)

Thanks!....

**Comment by Agri-Life09** [comment]
What do you need the one I the vehicle to work for. The one you need this the one om the hud in the bottom right of the screen. The vehicle one has nothing to do with this mod or the author of this mod

**Comment by dinogk** [comment]
I'm just saying that once you enable the mod, the displays on the vehicles are all on zero. And yes, realisticly playing it's good to have those indicators running.

**Comment by Agri-Life09** [comment]
Ah, right. I thought you was meaning that they weren't working before.

**Comment by SbSh-DNA-ModDing** [comment]
temperatues etc. are deaktivated and not synced in mp by giants, you have to reactivate it and sync it by self, also the other features, heatPerMS, coolingBYwind, FANenabled..... etc.

**Comment by MathiasHun** [comment]
Fixed, will be uploaded soon. Tested in SP
