### ISSUE TITLE
Many breakdowns 

### ISSUE THREAD

**Issue by Agri-Life09** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#13]
I don't know if it's just bad luck or whether the number of breakdowns is too high because I've had 2 engine failures on the same tractor (although I did only reset the tractor which fixed the issue) then lights stopped working on another and now a generator failure on another tractor. It may be that the chance of breakdowns needs to be decreased slightly otherwise it's bad luck for me lol.

**Comment by MathiasHun** [comment]
Fixed, will be uploaded soon
