### ISSUE TITLE
Several issues currently with repairs and multiplayer

### ISSUE THREAD

**Issue by Wreyth** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#14]
Hi there , first off awesome work so far.

Few issues first and most importantly can't do the base game repair it just pops up the message must be repaired in the RVB menu. If the vehicles condition drops to 0 and it shuts down can't repair in the rvb menu at all only inspection or periodic service if it has enough hours to do so. currently if this happens both single player and multiplayer we have to use easy dev tools to repair to get it to start again. this is only an issue with the base game condition and repair. So base game condition can drop to 0% and stop working but the inspection brings up no issues and no ability to repair it when this happens.

2nd each person has to have admin to change the repair option back to only at shop individually and it doesn't save that setting so every restart we have to change it again individually.

3rd it is currently set to only farm managers can do the inspections and repairs and no option to change that.

**Comment by TacticalOreo** [comment]
I second this

**Comment by Wreyth** [comment]
Wellness Check there buddy..... you been radio silent for 2 months

**Comment by MathiasHun** [comment]
2nd and 3rd fixed
