### ISSUE TITLE
doesnt work with the manure system mod

### ISSUE THREAD

**Issue by kfarrell3** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#17]
it causes a save game to brick when active with the manure system, i have a screenshot of the part of the log that has the error, this is the base game map with just this mod and the manure system mod
![Farming Simulator 22 4_1_2024 10_44_02 PM](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/68313730/921a320b-77b3-46ec-85f3-5e0af5adadae)

**Comment by MathiasHun** [comment]
I ran into it once, there was a coding error, I hope so
