### ISSUE TITLE
HUD position fuel text wrong..

### ISSUE THREAD

**Issue by FirenzeIT** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#18]
Hi @MathiasHun and @vitalii2011, the HUD regarding the fuel in the lower right corner (see screenshot below), is not aligned accurately (missing text), what is the correct procedure to fix this problem? Is it possible to fix it directly by you? Or please explain to me, how and what should I modify? Thank you.

![20240408232944_1](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/113168067/287b2a8f-1992-47b3-ba1c-37d31f4225b8)

**Comment by MathiasHun** [comment]
I hope I fixed it. I will upload it soon
