### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by BRADP1980** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#19]
Hello. Not really an issue just a question as i was not sure where to post this. Has there been any updates at all to the mod? I think the last one i downloaded was back in mid march. I keep checking but says no new releases. if there is a new copy how can i get a copy of it? Thanks much.

**Comment by MathiasHun** [comment]
Hello, unfortunately I couldn't develop it due to lack of time. We will post an update soon

**Comment by BRADP1980** [comment]
Thank you very much for the update. Looking forward to the upcomming updates as i am enjoying the mod on my realistic rollplay with friends.

**Comment by BRADP1980** [comment]
I see you have updated the config and other things to this mod. How do i update them on my end? I still have like the original copy with 0 updates and things are breaking down a lot. thank you.

**Comment by MathiasHun** [comment]
The full package has not yet been uploaded
A little teaser
https://www.youtube.com/watch?v=B1dIBnbpYaU

**Comment by MathiasHun** [comment]
Uploaded
