### ISSUE TITLE
Breakdown types

### ISSUE THREAD

**Issue by Drmattymd** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#2]
Game does not have gasoline as a fuel type so sparkplugs would not be a legitimate breakdown issue as diesel engines do not have sparkplugs.

Also there should be something that shows repair time remaining or finish time eta

**Comment by DrewCZ** [comment]
yep, you are right, but diesel engines can use glow plugs.
anyway, mechanics for sparkplugs can be used for injection nozzles? 
I agree, that in the game almost all engines are diesel. maybe another setting for each vehicle, with a preselected "diesel" value?

**Comment by MathiasHun** [comment]
> Game does not have gasoline as a fuel type so sparkplugs would not be a legitimate breakdown issue as diesel engines do not have sparkplugs.

You're right, I skipped over that.

> Also there should be something that shows repair time remaining or finish time eta

It should appear in vehicle hud. 
It will be included in the menu section during an update, its place is already there.
I planned to put it in the help menu, but I discarded the idea

**Comment by MathiasHun** [comment]
> yep, you are right, but diesel engines can use glow plugs.
> anyway, mechanics for sparkplugs can be used for injection nozzles?
> I agree, that in the game almost all engines are diesel. maybe another setting for each vehicle, with a preselected "diesel" value?

I think I'll just rewrite the text part:
spark plug -> glow plug.
But I will modify it a little so that this error can be more noticeable in cold weather.
