### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by LSMT-elMatador** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#21]
Hallo, tolle Mod!
Leider sind die ganzen Anzeigen im Tacho nur auf 100% Hud größe angelegt. 
Kann man dan an die Spieleinstellungen hängen? So dass, wenn ich mit einem Ingame HUD von 80% spiele, die Anzeigen ebenso an der richtigen Stelle habe? oder muss ich das im Script abändern?

![fsScreen_2024_06_06_18_41_26](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/73357386/bf8fe7b3-af8c-42bb-a0b3-d9270ab78bb7)
So würde es gehören, Ist mir leider zu groß!

![fsScreen_2024_06_06_18_44_29](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/73357386/8f2d33b1-88c5-426b-8375-938f8c7070aa)
So ist es in der Größe, in der ich es gerne hätte. Ingame Hud Größe 80%!

**Comment by MathiasHun** [comment]
Ich denke, es kann geändert werden, wenn ich es finde.
Ich habe diese Einstellung überprüft, bevor ich Ihre Fehlermeldung gelesen habe. Die Symbole verschieben sich dadurch, wenn nicht 100 %
