### ISSUE TITLE
Error on dedicated multiplayer server

### ISSUE THREAD

**Issue by bvnovaes** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#22]
First, congrats on this mod, it's really cool!

I stumbled upon an error when using the mod on a dedicated multiplayer server. Players can't log in. The problem does not occur when opening a multiplayer game locally.

The log file shows errors on lines 1314 and 1315. As a test, I removed these lines and all the references to these variables in the Lua file (declarations, reads, writes, etc.). After this, I tried to log in again and it worked fine. Looking at the savegame for both the dedicated multiplayer server and the local multiplayer game, the vehicle tags do not show the two parameters that caused the error on lines 1314 and 1315: lifeage and age.

Let me know if you need any additional info.

[log.txt](https://github.com/user-attachments/files/15673837/log.txt)

[vehicles.txt](https://github.com/user-attachments/files/15674805/vehicles.txt)

* The vehicles.txt is just to attach to the issue; on my server, it is an XML file as it should be.

**Comment by MathiasHun** [comment]
Sorry MP from players. After the last small cleaning, I only checked SP, not MP. 
Few minutes and I'll fixed
