### ISSUE TITLE
Setting for vehicle breakdown.

### ISSUE THREAD

**Issue by BRADP1980** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#25]
When setting up the settings for the vehicle breakdown from slow/medium or fast, it doesn't stay set . it keeps going back to slow.

**Comment by MathiasHun** [comment]
I'll check, I don't have time today

**Comment by BRADP1980** [comment]
Thank you. Yes i see a few issues with the mod but i am still using it on my server MP roll play. we love using all the realistic mods as we play realistic. cant wait for all the bugs to be repaired on this as we all love using this mod. I use this on my MP roll play server so if you need any feedback or someone to help test new version, I am more then happy to help. Thank you!

**Comment by MathiasHun** [comment]
Fixed, v0.8.7.0
