### ISSUE TITLE
Vehicle battery icon doesn't displaying in the HUD when is too low

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#26]
Hello,

I wanna ask something, if the tractor is far away from workshop then how can i move the vehicle in the workshop to recharge the battery? is there a away so i can remove the battery from the vehicle and charge it? Also i noticed that battery went in 25% and the tractor was unable to start and not any HUD lights are enabled in the tractor HUD, is that by design? 

![FarmingSimulator2022Game_2024-06-08_15-10-33](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/3636159/353de4ab-a7f2-4c66-b75a-bfc4c2f8b10c)
![FarmingSimulator2022Game_2024-06-08_15-10-22](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/3636159/0b50bc0f-fbac-4981-b04b-de5c412ee47e)

- Thanks!

**Comment by BRADP1980** [comment]
you could always turn off repair in workshop only or get something like the tow chain/rope mod or tow truck/rollback mods to tow it. I use the chain.

**Comment by westor7** [comment]
> you could always turn off repair in workshop only or get something like the tow chain/rope mod or tow truck/rollback mods to tow it. I use the chain.

The tractor is in the field and too far away from workshop lol

**Comment by BRADP1980** [comment]
> > you could always turn off repair in workshop only or get something like the tow chain/rope mod or tow truck/rollback mods to tow it. I use the chain.
> 
> The tractor is in the field and too far away from workshop lol

Go into the breakdown settings when you hit alt W and turn off where it says only repair in vehicle workshop. that will allow you to fix it anywhere it breaks down.

**Comment by westor7** [comment]
Ok that option is ok but it still a HUD problem that when the battery is too low that the tractor cannot start then there is not any alert in the HUD not any icon appearing to inform me that is too low and need charging or when the battery is dead is not displaying the battery icon in the HUD

**Comment by MathiasHun** [comment]
> Ok that option is ok but it still a HUD problem that when the battery is too low that the tractor cannot start then there is not any alert in the HUD not any icon appearing to inform me that is too low and need charging or when the battery is dead is not displaying the battery icon in the HUD

HUD is not complete in this respect.
In the beta version, the priority is the location of the icons and that they appear correctly for everyone. There was also a problem with the location.
https://postimg.cc/dDC94Ms9
(In-Game HUD Scale) this is already fixed
Of course, you will know the battery drain

**Comment by MathiasHun** [comment]
You won't know when the battery is low, there will be no battery icon when the battery is low.
It only appears if the generator is faulty.
