### ISSUE TITLE
Is it possible to disable the "You are using..." message from appearing every time start the game?

### ISSUE THREAD

**Issue by vitalii2011** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#27]
![fsScreen_2024_06_08_16_47_35](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/41552153/152f8a5c-443c-4d27-b210-baf38ba19752)
I understood  this from the 1(9)st time. )))

**Comment by MathiasHun** [comment]
It will appear only once in the next edition.
I didn't think it was important to develop this part further in the Beta version

**Comment by vitalii2011** [comment]
In 0.8.7.1, this "repeat message every time the game starts" returned.

**Comment by vitalii2011** [comment]
... and remained in 0.8.8.0. It's a bit tiring. :)
How/Where can I fix this?
By the way, the mod is getting better. I like it. Thank you.

**Comment by MathiasHun** [comment]
SP or MP?

**Comment by vitalii2011** [comment]
SP

**Comment by MathiasHun** [comment]
Fixed

**Comment by vitalii2011** [comment]
Thanks!
