### ISSUE TITLE
Inspection vs Condition

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#29]
Hello,

When i send for inspection the vehicle then it says nothing needs to be fixed but the condition on the tractor is not going to **100%** so how can the condition be **36%** and it doesn't need any fix? and how can the condition reach 100% ?

![FarmingSimulator2022Game_2024-06-08_20-26-55](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/3636159/58b1597c-978a-4eab-822d-bce3b50d4a30)

- Thanks!

**Comment by MathiasHun** [comment]
That's why it's a Beta version.
It will be included in the next release, if you don't find part damage, but the damage has already reached, for example, 30%, it can still be repaired.
