### ISSUE TITLE
Random vehicle battery drops to 25% on every game load

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#30]
Hello,

I noticed that when i save and close the game and open it again then in random vehicles the battery is dropping in 25% for no reason, i think this is because when i save the game the machine is working and uppon quit the save is saving the machine state that is running-working and then this is draining the battery, not sure but just a guess.

- Thanks!

**Comment by MathiasHun** [comment]
SP or MP?

**Comment by westor7** [comment]
SP

**Comment by MathiasHun** [comment]
But if you play SP, the game won't run, so the battery can't be drained. MP yes.
But I will test and see

**Comment by MathiasHun** [comment]
This issue still exists?

**Comment by westor7** [comment]
It's fixed!
