### ISSUE TITLE
Courseplay conflict

### ISSUE THREAD

**Issue by lookee86** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#31]
It looks like there is still conflict with courseplay. Window randomly pops up saying "The mechanic cannot repair this vehicle, visit RVB Service".

**Comment by MathiasHun** [comment]
FS22_AutoDrive? Active, are you using it?

**Comment by lookee86** [comment]
Yes. Im usind Autodrive

**Comment by MathiasHun** [comment]
Fixed
