### ISSUE TITLE
saw courseplay issue, disabled it, cannot join mp server

### ISSUE THREAD

**Issue by thebikwirm** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#33]
2024-06-10 05:26 Warning (script): 'streamWriteInt16': Argument 1 has wrong type. Expected: Int. Actual: Nil 
2024-06-10 05:26   2024-06-10 05:26 D:\auto_builder\cache\svn\ebac29df05e8259ab65b77112f6766d3\src\base\scripting\lua\LuaScriptSystem.cpp (903)2024-06-10 05:26 : 2024-06-10 05:26 expectedType == Value::VoidType || expectedType == Value::ClassType
2024-06-10 05:26 LUA call stack:
  =C:/Users/Administrator/Documents/My Games/FarmingSimulator2022/mods/FS22_gameplay_Real_Vehicle_Breakdowns/scripts/vehicles/specializations/VehicleBreakdowns.lua (1315) : streamWriteInt16
  dataS/scripts/specialization/SpecializationUtil.lua (23)
  dataS/scripts/vehicles/Vehicle.lua (1686) : raiseEvent
  dataS/scripts/network/Server.lua (200) : postWriteStream
  dataS/scripts/BaseMission.lua (1148) : update
  dataS/scripts/FSBaseMission.lua (1983) : update
  dataS/scripts/missions/mission00.lua (577) : update
  dataS/scripts/main.lua (1299) : update

**Comment by MathiasHun** [comment]
Fixed issue#22
If I remember correctly, this link has the corrected one.  (I m writing from my phone)

https://sharemods.com/bt0efm7ohcdv/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

**Comment by thebikwirm** [comment]
is/has the courplay issue been fixed?

**Comment by MathiasHun** [comment]
There are no errors in the log.
Other automatic repair methods may cause errors. FS22_AutoDrive conflict in progress

**Comment by MathiasHun** [comment]
Fixed
