### ISSUE TITLE
[0.8.6.0]: Battery dropped at 25% while engine was running

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#35]
Hello,

I was fertilizing the field and lights turned off and battery dropped to **25%** while i was driving the tractor, i was trying to switch off but i couldn't it doesn't let me switch off the tractor.

**NOTE**: Not any HUD battery (red) icon enabled due this case.

![FarmingSimulator2022Game_2024-06-14_09-39-29](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/3636159/de5c44b7-c55e-442d-b88d-b99db64158d0)

- Thanks!

**Comment by MathiasHun** [comment]
You're right, one condition was left out.

Fixed
https://sharemods.com/xo6i1yuoawco/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

**Comment by westor7** [comment]
After this fix the lights+beacons are auto-turning off after some seconds but battery remains 100% so its not totally fixed

Short video: https://ufile.io/rpv28x66

Do you have any discord so i can talk there directly on you?

**Comment by MathiasHun** [comment]
I already fixed it. The download link is also fixed
