### ISSUE TITLE
AutoDrive

### ISSUE THREAD

**Issue by LSMT-elMatador** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#36]
EN
Hello, great, the mod is getting better and better!
However, I now have the problem that AD can no longer reach targets.
So:
You send a vehicle to target "x"!
It drives off properly!
It also finds the target, but when it reaches the target, AD is not switched off!
That means the vehicle drives in the lowest gear until the tank or the map runs out, just straight ahead!

DE
Hallo, Toll, die Mod wird immer besser!
allerdings habe ich nun das Problem, das AD keine Ziele mehr erreichen kann.
Also: 
Man sendet ein Fahrzeug zu Ziel "x"! 
Er fährt ordnungsgemäß los! 
Findet auch das Ziel, Aber beim erreichen des Zieles wird AD Nicht abgeschaltet!
Das heisst, das Fahrzeug fährt im kleinsten Gang, bis der Tank oder die Karte zu ende ist, einfach mal gerade aus!

**Comment by LSMT-elMatador** [comment]
EN
Even if I want to pick something up somewhere in "load - deliver" mode, AD cannot switch to the next destination point at the destination point, even if it is fully loaded, and thus cannot complete the "transport order". This mod, in its current form, unfortunately makes AD ineffective! And therefore unusable for many players!
What a pity!
DE
Auch wenn ich im "laden - liefern" Modus irgendwo etwas abholen möchte, kann AD, selbst wenn voll beladen wurde, beim zielpunkt nicht zum nächsten Zielpunkt weiter schalten, und somit den "Transportauftrag" nicht zu ende führen. Diese Mod, in Ihrer jetzigen Form,  macht AD leider wirkungslos! Und somit für viele Spieler unbrauchbar!
Schade!

**Comment by MathiasHun** [comment]
Don't give up, I'll make it another way. That's why I sent the eyes.

**Comment by MathiasHun** [comment]
Currently, if the vehicle is damaged, it will not go to the repair shop to fix it. I'm still working on it.

https://sharemods.com/jlpoqcyami2a/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

**Comment by LSMT-elMatador** [comment]
EN
I will test version 0.8.6.2 and share my experiences here!
DE
Ich werde die Version 0.8.6.2 testen und meine Erfahrungen hier kundtun!

**Comment by LSMT-elMatador** [comment]
Now it works perfect with AutoDrive!
Thank you very much!
