### ISSUE TITLE
Beacons should turn off too when there is no battery

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#37]
Hello,

I saw that when the battery is too low the lights are turning off but if someone has beacons on they are working as i think they should not.

- Thanks!

**Comment by MathiasHun** [comment]
I think there is no problem with it, but the engine cannot be stopped.

I didn't plan to turn it off, there is a minimal charge in the battery. :) :(

**Comment by MathiasHun** [comment]
Fixed, this is subject to change

https://sharemods.com/jlpoqcyami2a/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

**Comment by MathiasHun** [comment]
Can I close?

**Comment by westor7** [comment]
Give me 1 day more to fully tested so i can give the feedback if any issues exists, thanks!

**Comment by westor7** [comment]
One thing that i've notice is that when the machine is turned off and i enable the beacons it doesn't start to drain battery, but it does with lights

**Comment by MathiasHun** [comment]
It's not in it yet
