### ISSUE TITLE
[0.8.6.2]: Periodic service does not reset damage bar

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#39]
Hello,

I used the periodic service but when the service finished then the damage bar does not reset at 100% (serviced) state.

![FarmingSimulator2022Game_2024-06-15_12-43-32](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/3636159/944af58a-f9d5-4fc1-a988-5ac1f1797b03)

- Thanks!

**Comment by RubberDuck01** [comment]
Same issue here. Neither Inspection nor Periodic Service reset the damage bar.

**Comment by MathiasHun** [comment]
After servicing and inspection, the damage bar will not change.
It will be included later (servicing), but even then the damage bar will not be 100%.

**Comment by westor7** [comment]
I think the damage bar should be restored at 100% when you service a machine otherwise the damage bar is useless.

**Comment by RubberDuck01** [comment]
> After servicing and inspection, the damage bar will not change. It will be included later (servicing), but even then the damage bar will not be 100%.

That will be a pure mess. What's the point of having a damage bar that cannot be reset?

I think this mod would benefit a lot from damage % for its functions. For example:

- 0% - 10% damage: everything works properly
- 10% - 25% damage: machines are still fine, they just use a tiny bit more fuel, they're less efficient
- 25% - 35% damage: 15% chance that the thermostat will fail
- 35% - 50% damage: 30% chance that the thermostat will fail, battery starts losing its charge
- 50% - 65% damage: 50% chance that the thermostat fails, battery loses its charge even faster, 15% chance that the machine won't start from the first try
- 65% - 75% damage: battery needs replacing (recharge battery as often as you'd like, but it always loses its charge very fast), machine is very likely to overheat during work
- 75% - 85% damage: further fuel consumption increases, machine is on its last legs and the issues need to get addressed as soon as possible
- over 85% damage: possibility of a blown engine (or something similar)? it'd be a costly repair and machine's value is reduced drastically.

I think that'd spice the gameplay up quite a bit. It's all about fine-tuning those %-ages and what issues it causes. However, at the same time, I wouldn't want to over-complicate things - keep it simple, add a new layer of complexity to the game, but don't overdo it. Afterall, FS is a game.

**Comment by MathiasHun** [comment]
Thermostat (150 operating hours)
Glow plug (2 operating hours)
Generator (180 operating hours)
Engine (210 operating hours)
Starter (3 operating hours)
Service is not ready yet, so it does not affect it

During vehicle operation, the operating hours of the above parts increase every minute, if they reach 95% of the set operating hours, an error is generated.

So every minute the damage bar of the vehicle gets worse. The greater the damage, the more it loses its power (basic FS22)

When repairing a vehicle, you can reach 100%, but not in all cases, it is randomly generated (monitors the age of the vehicle)

**Comment by viniciuspir** [comment]
Mathias, I think the operating hours of Glow Plug and Starter its to low, maybe 5 for plug and 10 for starter is a little bit more ralistc, after a little jon, my Top liner needs to do another inspection and change the plug, it's turning me crazy with the costs!!!

**Comment by westor7** [comment]
> Mathias, I think the operating hours of Glow Plug and Starter its to low, maybe 5 for plug and 10 for starter is a little bit more ralistc

I've created a PR about it. #38
