### ISSUE TITLE
[0.8.6.2]: After AI finish the work battery continue drops until goes empty

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#40]
Hello,

I've notice that when i send an AI worker to drive somewhere after he completes my order and the game says AI driver completes then the battery continues to drop as it shouldn't.

- Thanks!

**Comment by westor7** [comment]
The same is happening when i manually turn off any machine, the battery keeps dropping for an unknown reason... so i have to keep on all the machines for ever LOL!

**Comment by MathiasHun** [comment]
Issue in MP game :(

**Comment by westor7** [comment]
It's fixed in SP
