### ISSUE TITLE
Autodrive issue

### ISSUE THREAD

**Issue by viniciuspir** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#41]
Hello guys, for some reason, after install and active the mod, I experienced the gear shifter problem with one lifter machine and a issue with autodrive, the vehicles aren`t stopping at correct place and for beacuse of that it doesn`t go to next waypoint,

example: Tractor unloanding combine on field 24 at Hof Bergmann map, when reach the field it continues straight at low speed, never stop. When manualy drive to unload and after complete ir and switch the command to go to unload point it detect the unload point, start unloading and when reach the designated point it goes foward and colide with the wall.

I inactivated the Real Breakdown and autodrive back to normal.

**Comment by MathiasHun** [comment]
This issue?

https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/issues/36

**Comment by viniciuspir** [comment]
Yep! Downloaded last version and now working fine! Thanks bro!!
