### ISSUE TITLE
Not compatible with AutoDrive

### ISSUE THREAD

**Issue by 0scarZulu** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#43]
ENG
As soon as RVB is active, vehicles controlled by Autodrive no longer stop at the destination point. They then continue in any direction.

GER
Sobald RVB aktiv ist halten die Fahrzeuge, welche mit Autodrive gesteuert werden, nicht mehr an dem Zielpunkt an. Sie fahren dann in irgendeine beliebige Richtung weiter.

Cheers

**Comment by MathiasHun** [comment]
This issue?

https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/issues/36

**Comment by 0scarZulu** [comment]
Yes, thank you :) I still had the 8.6.1 :D It works with the new 6.3. Thank you :)
