### ISSUE TITLE
how fix this do I place something

### ISSUE THREAD

**Issue by thebikwirm** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#46]
![image](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/96290127/aa31dd9a-6e5b-4fe7-b00e-a5660a3b98db)

**Comment by thebikwirm** [comment]
also something like jumper cables would be nice for the battery stuff

**Comment by westor7** [comment]
Read the mod description it says how to enter in RVB repair service menu.

https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/blob/main/modDesc.xml#L9-L44

**Comment by MathiasHun** [comment]
> also something like jumper cables would be nice for the battery stuff

Unfortunately, I'm not good at 3D modeling

**Comment by thebikwirm** [comment]
> Read the mod description it says how to enter in RVB repair service menu.
> 
> https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/blob/main/modDesc.xml#L9-L44

Any chance these things could be done via the repair menu as well?

**Comment by thebikwirm** [comment]
> > also something like jumper cables would be nice for the battery stuff
> 
> Unfortunately, I'm not good at 3D modeling

What would you need need modelled for that, the jumper handles and a basic coil?
Or even just make it a non visual thing

**Comment by thebikwirm** [comment]
so what do I press from here to recharge the battery, do I just leave it in the workshop area?
![image](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/96290127/649ec773-3151-4099-9e70-f7888c3e32ef)

**Comment by westor7** [comment]
> so what do I press from here to recharge the battery, do I just leave it in the workshop area? ![image](https://private-user-images.githubusercontent.com/96290127/340979134-649ec773-3151-4099-9e70-f7888c3e32ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODQwMjMsIm5iZiI6MTcxODc4MzcyMywicGF0aCI6Ii85NjI5MDEyNy8zNDA5NzkxMzQtNjQ5ZWM3NzMtMzE1MS00MDk5LTllNzAtZjc4ODhjM2UzMmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZWY1MDMxOTU4ZTM0YWJmZWRlNDViNjJmMGY4MDk2MDM1MTFiYTA4YTJjYjhlNTM4OTQxYzUyNTM4NjEzYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.48sS2x1P3-xQe-prizFvG8lgq2nuwqZkYNFx5fD9SSk)

You can disable the option to fix in workshop only, and then you access in the RVB menu and charging the battery.

**Comment by thebikwirm** [comment]
that was what I was doing
how do I charge it, do I stay in the menu or what

**Comment by thebikwirm** [comment]
do I click on something

**Comment by thebikwirm** [comment]
got it it now works wasnt showing up before
