### ISSUE TITLE
[0.8.6.3] !!! MOD CONFLICTED OF TWINE/NET !!! [ RESOLVED ]

### ISSUE THREAD

**Issue by s4dnz** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#47]
Hello!

I had problems with my control when drunk and unable to use control. I had over 50 mods at files so I attempted to narrow down to finds out what cause of problems.
After few testing between mod following as:

- Twine Addon
- Net Addon
- Real Vehicle Breakdown
- CSZ pack
- Maunal Attachment

With using my "test" file that simplify narrowed down to make easier disabled or active mods. I had managed to diagnosed to conflicted problem. There nothing problem with CSZ pack so I rules out because twine and net both had build in optional as following as (Twine and Net had both them mod are same): 
Configation: Vehicle (should be attach type optional pops up)
Attachment types: 3-Points.

As the mod ONLY used Real Vehicle Breakdown and Net/Twine are on, whatever reason I attach with the tractor to twine or net 3-points, that error would end up throwing up.
![fsScreen_2024_06_18_13_07_53](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/104271391/920ec416-cfbc-4c10-8858-194efe648ac2)

That where problem become plays. No matter what Maunal attachment is on or off, it's caused main problem with Real Vehicle Breakdown conflicted with Net and Twine mods. That why my control went drunked and unable usage of control. That cause of conflicts due unplayable without control are proper functions.

LOG: 
[log.txt](https://github.com/user-attachments/files/15886767/log.txt)

**Comment by westor7** [comment]
It seems you are using `0.8.6.1` version , does this happening if you update to the latest one ?

https://sharemods.com/jqyaviwgygao/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

**Comment by s4dnz** [comment]
> It seems you are using `0.8.6.1` version , does this happening if you update to the latest one ?
> 
> https://sharemods.com/jqyaviwgygao/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

Ah sorry! I I forgot to update and I was thinking to overlooked update logs there none about that issues. Sadly, as I had update mod and it's still carried over the error underlying as same error code. Updating made no different.
![20240618194409_1](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/104271391/a4331c15-a163-468e-a2c2-fd21b59c22b2)

Like it's simpify as only Net and Twine mod and REAL Vehicle Breakdown mod are actived. Gave same issues between REAL Vehicle Breakdown conflicted with Net Addon and Twine Addon.
I belived it's very sneaky well hidden bugs because error won't ACTIVED till you bought net/twine with 3-point as you attach it then that where bug come play.

Log: 
[log.txt](https://github.com/user-attachments/files/15891120/log.txt)

**Comment by MathiasHun** [comment]
Fixed, Download the latest developer version

**Comment by MathiasHun** [comment]
The error has been resolved?

**Comment by SteveSpuller** [comment]
I hope this is the right place but the breakdown mod wont let any self propelled sprayer spray or spread over 6mph, 10kph? I have tried every one in the in game mod hub and a few other mods, I have the latest 0.8.6.3 now but did not work with 0.8.6.0
