### ISSUE TITLE
Fahrzeug geht nicht aus | Vehicle does not switch off

### ISSUE THREAD

**Issue by 0scarZulu** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#49]
Hallo :) 

[ENG]
One error is apparently that you can no longer switch off the vehicle's engine. Everything is fine. However, it might be cool to have it turn off at the latest during the inspection or even during the repair, so that it doesn't stand there with the engine running all the time and the operating hours go up. Or if it is discovered during the inspection that the engine has a fault, you are then forced to repair it. 
Now my tractor is standing there, the engine is running and as long as it is being repaired, the operating hours keep going up. :D Is that what you want? 

[DEU]
ein Fehler ist ja offenbar das man den Motor des Fahrzeuges nicht mehr abstellen kann. Alles Fine. Hier wäre aber eventuell cool das er spätestens bei der Inspektion oder sogar bei der Reparatur dann aus geht und nicht die ganze Zeit mit laufenden Motor da steht und somit die Betriebsstunden nach oben gehen. Oder wenn dann bei der Inspektion festgestellt wird das der Motor ein Fehler hat man dann gezwungen ist zu reparieren. 
Jetzt steht mein Traktor da, der Motor läuft und solange wie die Reparatur ist steigen munter die Betriebsstunden. :D Ist das so gewollt? 

Cheers

**Comment by westor7** [comment]
I had the same issue with the vehicle that was not turned off, it seems that is fixed in the latest version , can you try the latest one and see if is fixed?

https://sharemods.com/3o14arppa4vn/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

**Comment by 0scarZulu** [comment]
I have the current version 0.8.6.3. I saw that the link was changed yesterday. Did they forget to raise the version number?

**Comment by MathiasHun** [comment]
Yes, this an issue.
The plan is to automatically stop the engine when repairs or inspections begin. It was working until now, but not after the update.

**Comment by 0scarZulu** [comment]
Ok. Thanks for the explanation. I am confident that you will fix this in the next update.
