### ISSUE TITLE
Is it possible to move "fuel consumption" under the "Fuel" icon?

### ISSUE THREAD

**Issue by vitalii2011** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#5]
![fsScreen_2024_03_08_12_24_43](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/41552153/89110f54-3f07-490a-8cc7-02a65622068d)

**Comment by MathiasHun** [comment]
Modified 
https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/blob/main/scripts/hud/RVB_HUD.lua

**Comment by vitalii2011** [comment]
Thank you! Everything is fine.
![fsScreen_2024_03_08_14_12_02](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/41552153/716fb6b1-6e1d-4f0f-867f-9ddae51945d8)
