### ISSUE TITLE
Korrekte Anzeige vom Ende | Correct display of the end

### ISSUE THREAD

**Issue by 0scarZulu** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#50]
Hallo 
[ENG]

a correct display of when a repair or inspection is completed would be desirable. In my case it now says that the maintenance will be completed at 13:15. But I don't know whether it will be that day or the next day. A display in the overview or something would be nice. Otherwise it's difficult to plan.

[DEU]
eine korrekte Anzeige wann eine Reparatur oder Inspektion abgeschlossen wird wäre noch wünschenswert. Bei mir stand jetzt das die Wartung um 13:15 abgeschlossen sein wird. Aber ich weiß nciht ob an diesem Tag oder am nächsten Tag. Da wäre eine ANzeige in der Übersicht oder so schön. SOnst kann man irgendwie schwer planen.

CHeers

**Comment by MathiasHun** [comment]
Currently, the maximum repair time is set to that day or tomorrow.
If you complete the repair today.
Example: 09:20
If you finish the repair tomorrow.
Example: tomorrow 09:20

**Comment by 0scarZulu** [comment]
![image](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/78980660/8e653466-a5f4-4583-a030-3042d0bebf42)
![image](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/78980660/85516973-6060-47e5-a17b-8634cbcdedce)
![image](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/78980660/fb08905b-e9cd-418a-a9f8-7755d0964851)

The vehicle inspection should only last until 16:05 or 16:08 as shown in the picture. Nevertheless, both vehicles are still in the inspection at 16:15 according to the overview. In my opinion, it is also incorrect that I can move both vehicles even though they are being inspected. 
This was tested with the current version 0.8.7.0.

Furthermore, I had 2 more errors in the log which are certainly related to the inspection.

![image](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/78980660/e1bd2643-5aa3-422d-b383-fb00b217e3e2)

**Comment by MathiasHun** [comment]
Fixed in my opinion
