### ISSUE TITLE
[0.8.6.3]: Beacons should auto-turn off on Inspection or Periodic Service

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#52]
Hello,

Currently when i use Inspection or Periodic Service on a vehicle it doesn't auto-turn off the vehicle beacons but it turns off the lights and the motor, i think it should also turn off the beacons under this case too.

**EDIT**: The motor of the vehicle is still running under this case but you cannot move the vehicle, this also sounds as bug too because the motor should also auto-turned off too.

- Thanks!

**Comment by MathiasHun** [comment]
When starting a repair, it only stops the engine automatically. He doesn't turn off the lights on purpose, the player should do something too. If you forget, you can charge the battery.

**Comment by westor7** [comment]
Why it doesn't turn off the lights + beacons and all the things on the vehicle as it starts to servicing the vehicle.. i suggest to add to turn the lights off + the beacons.
