### ISSUE TITLE
Battery loses power over time without lights (MP only)

### ISSUE THREAD

**Issue by d23vaa** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#53]
Battery loses too much power over time.

**Comment by westor7** [comment]
Battery lose **5%** each time when you turn on the vehicle, and if you leave lights enable without turning on the vehicle.

**Comment by d23vaa** [comment]
Yes i know but my battery lose power without anything. ONLY in MP (dedicated server)

**Comment by lookee86** [comment]
> Yes i know but my battery lose power without anything. ONLY in MP (dedicated server)

In SP I have problem with battery. When batery discharge to 5% I load it up to 100%. After chargin I can start engine but I cant turn it off. When I reload save game the batery is again discharged (it have only 5%).

**Comment by 0scarZulu** [comment]
I can always charge the battery further within a day. I stopped at 400%. The next day it is only at 100% again
