### ISSUE TITLE
Self Propelled sprayers working speed not over 6mph

### ISSUE THREAD

**Issue by SteveSpuller** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#55]
self propelled sprayer, everyone in the in game mod hub with not work over 6mph.  Base map, no other mods other than breakdown mod and each sprayer separate, no errors or warnings  Same in 0.8.6.0 as in 0.8.6.3.  Sweet mod by the way

**Comment by leo32128fs** [comment]
Same problem here in 0.8.7.2

**Comment by SteveSpuller** [comment]
yeah ha, I think thats what I am up to now but no ones responded to this in over a month

**Comment by MathiasHun** [comment]
Sorry, I fixed it now, please it download
