### ISSUE TITLE
[0.8.7.0]: Beacons does not drain battery when motor is off

### ISSUE THREAD

**Issue by westor7** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#56]
Hello,

I've noticed that beacons are not draining battery when are enabled and the motor is turned off, normally it should because its using power from battery (as lights too).

- Thanks!

**Comment by MathiasHun** [comment]
I know about it, but thanks. I want to change that part, that's why it hasn't been included yet.

**Comment by MathiasHun** [comment]
Fixed, [Download the latest developer version](https://sharemods.com/1ncbjnwtgv61/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html)
