### ISSUE TITLE
Problem with route end point - AutoDrive

### ISSUE THREAD

**Issue by AlecAsobu** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#57]
I experience this problem only when I activate RVB. The AI ​​of the Autodrive mod is no longer able to recognize the route endpoints and prevents the normal functioning of the system. Additionally, I detected that autodrive stopped notifying the jobs, it is possible that the error has to do with it.
I thought it could be another mod or even the game, I have already verified that this error is only active when the RVB mod is active.

**Comment by 0scarZulu** [comment]
I had the same problem. But with the current version, this error no longer occurs in conjunction with AutoDrive.

https://sharemods.com/3o14arppa4vn/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html
