### ISSUE TITLE
menu freezes

### ISSUE THREAD

**Issue by danyelvl** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#63]
1- it all worked, but a few minutes later the menu freezes when opened without any vehicle in the workshop (the last vehicle that was there appears) this only occurs when activated to only work in the workshop, I use a lot of mods so I'm still going to test it to see.

 2- Some mod vehicles are being treated as implements and do not appear in the list, the "f" menu also does not appear unless there is another vehicle that the mod recognizes. I believe that it should list everyone by default.

3- "Added opening new RVB menu. You can also open the RVB menu in the basic vehicle workshop trigger point. You can turn this off in the settings."

This works fine but we can't configure the vehicles, if you have the option to configure them too that would be perfect

**Comment by danyelvl** [comment]
1 ...
right, the mobile workshop from mod https://www.kingmods.net/pt/fs22/mods/28707/pacote-de-caixa-de-ferramentas
 when near the sliding gate of this mod
https://www.kingmods.net/pt/fs22/mods/25569/pacote-de-cercas-brasileiras
makes the menu freeze when opening.
However, the menu still freezes when opening and closing it a few times

(sorry for my English, I'm using a translator)

**Comment by MathiasHun** [comment]
I don't experience any freezes.
The Tool Box Pack generates an error, I'll fix it if I can

**Comment by danyelvl** [comment]
It seems that when you drop the mobile workshop near some objects and try to open the menu without any vehicle nearby, the menu freezes. I don't know if they are the placeable decorative objects or the objects we buy from the menu like vehicles.

Anyway, with vehicles nearby it works well, great mod playing with much more immersion now lol

**Comment by AlecAsobu** [comment]
I experienced a similar error, but my freeze happened with the vehicle inside an American workshop and in the service menu.

**Comment by danyelvl** [comment]
> I had a similar error, but the crash happened with the vehicle inside an American workshop and in the service menu.

Well for me it works well as long as I have a vehicle close to a workshop, if I accidentally open the menu without any vehicle it usually freezes.

**Comment by MathiasHun** [comment]
Fixed?
