### ISSUE TITLE
Translation and Scrollen

### ISSUE THREAD

**Issue by hecke82** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#64]
Hello, I just did the 0.8.7.0 in the mod folder and In the menu it shows partly German and partly English. And when I move in the vehicle overview with the scroll wheel, I also move in my view combined with PlayerActionCamera Mod.  Ansonten ein Super Mod / Otherwise a great mod

**Comment by MathiasHun** [comment]
I think it's because I tiredly modified the package in the evening and copied the English into the German translation.

I'll change it right away

Edit:
You downloaded this
https://sharemods.com/1ncbjnwtgv61/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

or the .zip file generated by github?

**Comment by hecke82** [comment]
Das war von hier, GitHub

**Comment by MathiasHun** [comment]
Try this, https://sharemods.com/8an984u87hw6/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html
