### ISSUE TITLE
No sell or vehicle customization

### ISSUE THREAD

**Issue by Monsterquake237** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#67]
When taking a tractor or equipment to the workshop area at the store, there is no sell option or customization option as it is replaced with the vehicle damage/repair screens. You can still sell in the menus but you cannot customise vehicles unless you buy them new.

**Comment by falcon470** [comment]
i had this same probelm you have to go back into the rvb screen and turn off the rvb menu, you can then turn it back on after your done

**Comment by Monsterquake237** [comment]
Thank you very much, this helps alot, i was trying to play realistically but this then became a issue.

**Comment by MathiasHun** [comment]
It will be in soon
