### ISSUE TITLE
A couple possible bugs

### ISSUE THREAD

**Issue by Randy-Butter-nubs** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#7]
Hello MathiasHun, Thank you for the mod I have been enjoying it a lot.  I have noted a couple of possible bugs that you may be interested in. 

First, a couple of vehicles don't maintain temperature when I am sitting in them idle, like waiting for an AI combine to finish a pass.  However if I get out of the vehicle it does maintain temp no problem.  It happens with the Case IH AFS Connect tractors mod by Karlfarms/Custom Modding and the 2022 JD 9RX by SiiD Modding, both on the official modhub.  It seems work fine with the base game tractors, and the pheonix 1982 mod and the Mack grain truck, and it happened on brand new tractors in game so it shouldn't be a breakdown.  I'm not a programmer so I have no clue what could be happening.  

Some vehicles also don't seem to warm up at all if I'm not in them.  This is for pretty much all of the one's I used. Again not a huge deal, just wanted to let you know in case that is a problem.

There are also some translations that aren't in english for those mods I said above, mainly the running while cold will sometimes be in another language (I'm sorry I don't know which). It's not a big deal, I know what they are telling me for the most part so I just wanted to let you know.  It also happened on the bottom right menu when it says how long the repair or maintenance will last.

Thank you again for the mod.  It has made it much more enjoyable to play.  Sorry if this is the wrong place, I have never posted on github before so delete this if you need to

**Comment by MathiasHun** [comment]
Someone reported that there was an FPS problem, so I took out a line, forgot to put it back.
So the maximum speed is 40 km/h, then drive at a maximum of 16 km/h, so the vehicle is not damaged, as soon as it reaches 30 degrees you can press the gas pedal.
There are untranslated texts in an English language file, but they are not used by the system.
In the showInfo() function, there was a text that was not added to the language files, it will happen now
