### ISSUE TITLE
motorized Vehicle

### ISSUE THREAD

**Issue by LSMT-elMatador** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#70]
Hello,
I noticed that with non-motorized vehicles (wheelbarrows, bicycles, handcarts) the message "don't drive too fast, your engine isn't warm enough yet" appears. I also noticed that vehicles where the handbrake isn't applied drain the battery. Engine off, no lights on!

DE

Hallo,
mir ist aufgefallen, das bei nicht motorisierte Fahrzeuge(Schubkarren, Fahrräder,Handwagen) auch die Meldung "fahre nicht zu schnell, Dein Motor ist noch nicht warm genug" kommt. Auch habe ich bemerkt, dass Fahrzeuge, bei denen keine Handbremse angezogen wurde, sich die Batterie entleert. Motor aus, Keine Lichter an!

**Comment by MathiasHun** [comment]
Compatibility with
FS22_lsfmFarmEquipmentPack
FS22_Wheelbarrow

[Download the latest developer version](https://sharemods.com/uxghfc8x1kmy/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html)
