### ISSUE TITLE
Add a FS22_JCB_Powerpack works for recharge battery + Massey Ferguson 950G Generator (FS22_MasseyFerguson_950G)..

### ISSUE THREAD

**Issue by FirenzeIT** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#71]
Hello @MathiasHun, as mentioned in the subject, we request the addition of the JCB powerpack to recharge the batteries to the vehicles, adding further realism, instead of clicking on recharge within the RVB mod. The JCB mod is cited in the subject line. 

And the battery bar (below the damage bar), for example for RIGITRAC, is not affected, in the sense, that it always remains at max charge.

![1248130_20240707035653_1](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/113168067/e95914ab-0adf-48a4-ab1d-391d6afc5f6a)
![1248130_20240707035828_1](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/113168067/6dcba6b0-4129-409d-94f8-7eae92520885)
![1248130_20240707035837_1](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/113168067/4943bf5c-3b46-4cb3-9dc7-dfa3b2587bc9)
![1248130_20240707043021_1](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/113168067/b56c1c6e-c5d3-4d87-8583-6b10d8f46f4c)
![1248130_20240707043031_1](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/113168067/72f3e731-b992-44f7-ae0f-094d983f5172)

**Comment by FirenzeIT** [comment]
Hi @MathiasHun, also with last update beta, not works with this JCB, but I have seen and tested the MF generator mentioned below, and it is better than the JCB one above, as MF is a real generator in its own right.. I have seen and tried also the MF generator mentioned below, can you try to make it compatible with your mod, and recharge batteries with this MF generator/genset please? Massey Ferguson 950G Generator.

Thank you.

![1248130_20240714151010_1](https://github.com/user-attachments/assets/885e82f4-8983-4695-a49a-07a12724af58)
![1248130_20240714152248_1](https://github.com/user-attachments/assets/2f5adb3a-9748-493e-b104-d4db9670f790)
![1248130_20240714152806_1](https://github.com/user-attachments/assets/b22be5ee-6a8b-4265-9893-ff65ca23c323)
![1248130_20240714153427_1](https://github.com/user-attachments/assets/c27ec644-853a-48a3-a464-52244c10d559)

**Comment by MathiasHun** [comment]
At the moment, I added it so that you have to go near it with the vehicle, then pressing the "R" button will start charging (RVB mod charging)

**Comment by FirenzeIT** [comment]
> At the moment, I added it so that you have to go near it with the vehicle, then pressing the "R" button will start charging (RVB mod charging)

Ok, and where are published the mod? I see last updated 5 days ago..

**Comment by MathiasHun** [comment]
On this page

**Comment by FirenzeIT** [comment]
> On this page

Sorry, but i don't see any link of the mod...

**Comment by MathiasHun** [comment]
Coming soon, I'm currently writing and testing it

**Comment by FirenzeIT** [comment]
Ah ok, nice bro 👍🏻

Il Ven 19 Lug 2024, 23:03 MathiasHU ***@***.***> ha scritto:

**Comment by MathiasHun** [comment]
I have not dealt with electric vehicles, there are still problems there
Update available

**Comment by MathiasHun** [comment]
The vehicles get a battery, it will be much better

**Comment by FirenzeIT** [comment]
Hi, for now it's working well with tractors (and other vehicles), but not electric's vehicle (such as mentioned before from you); but not appear any ETA's time of charging battery (used last update v0.8.8.0 of RVB)... 

![1248130_20240725011147_1](https://github.com/user-attachments/assets/cd1105e7-5c3a-4aab-bbb0-d717fe6164d3)

**Comment by MathiasHun** [comment]
Appears in the lower right corner when you are near the vehicle. It is not displayed in the (F1) window in the upper left corner. It appears when using a factory charging station, but the current version does not include it. 
I can't develop it for a few days, but the next version is almost ready. Vehicles were given a battery as if it were an electric vehicle. Thus, the charging station will already detect diesel vehicles.

Which mod includes the extra fuel info bar?

**Comment by FirenzeIT** [comment]
> Appears in the lower right corner when you are near the vehicle. It is not displayed in the (F1) window in the upper left corner. It appears when using a factory charging station, but the current version does not include it. I can't develop it for a few days, but the next version is almost ready. Vehicles were given a battery as if it were an electric vehicle. Thus, the charging station will already detect diesel vehicles.
> 
> Which mod includes the extra fuel info bar?

Ah ok, understood.  I don't see in right corner, i try another yet. The mod of the extra fuel it's FS22_DefPack (ADBlue) v1.0.0.1 from gitlab (author: Hans).

Probably this evening i write and attach here, an Italian's ITA language translation of this mod 👍🏻 

PS. Errors/failed to load on Alma's map and also on Carpathian Countryside PC only version:
2024-07-25 21:48   Info: [RVB] Failed to add specialization trainTrailer
2024-07-25 21:48   Info: [RVB] Failed to add specialization trainTimberTrailer
2024-07-25 21:48   Info: [RVB] Failed to add specialization conveyorBelt
2024-07-25 21:48   Info: [RVB] Failed to add specialization pickupConveyorBelt

**Comment by MathiasHun** [comment]
> PS. Errors/failed to load on Alma's map and also on Carpathian Countryside PC only version:
> 2024-07-25 21:48 Info: [RVB] Failed to add specialization trainTrailer
> 2024-07-25 21:48 Info: [RVB] Failed to add specialization trainTimberTrailer
> 2024-07-25 21:48 Info: [RVB] Failed to add specialization conveyorBelt
> 2024-07-25 21:48 Info: [RVB] Failed to add specialization pickupConveyorBelt

This is not a errors!
trainTrailer, trainTimberTrailer, ...  We do not add the specialization to the vehicles in the list
