### ISSUE TITLE
Doubt about battery recharging time during vehicle operation

### ISSUE THREAD

**Issue by viniciuspir** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#72]
Mathias, I have an issue with battery discharge during harvest operation using the FUEL SAVE mode of CoursePlay. Even with the generator in good condition, there is no time to charge the battery every time the NPC start the engine and cosume the 5% of start. When the vehicles are in harvest operation the trucks or tractors stop due to battery dead.

Any chance to speed up the charging of battery??

**Comment by MathiasHun** [comment]
I will change it to the following.

When starting the engine, the battery is reduced by 2%.
When the engine is running, it charges the battery by 1%.

**Comment by viniciuspir** [comment]
I think it will work, I will give you a feedback when you release the modification and test it. Thanks buddy!

**Comment by MathiasHun** [comment]
Update available

**Comment by viniciuspir** [comment]
Already downloaded, test in progress! Thanks man!

**Comment by viniciuspir** [comment]
I got one Issue:
When open the menu it shows only one vehicle, but when I take another vehicle to workshop it appears in the menu, but when turn off out of workshp it desapear and continues to show only the first vehicle. I extracted the message below from the Log:

 Warning: Missing l10n 'input_ACTIVATE_BATTERY' in mod 'FS22_gameplay_Real_Vehicle_Breakdowns'

**Comment by MathiasHun** [comment]
I already fixed it, I noticed it too. Thanks

**Comment by viniciuspir** [comment]
The Warning desapeared , but I have no vehicle list. I have 6 vehicles but only one appears in the list, the others only appears when I take them to the workshop and when I take them out, they desapears again, keeping the one I mentioned. I tried to remove mods I installed before I got this issue, but no result.

**Comment by MathiasHun** [comment]
RVB settings -> Repair only in the vehicle workshop? It should be turned off

**Comment by viniciuspir** [comment]
Yep, it was my fault. I didn't realise how this option was working, I thought it was to repair in the workshop only and the list continues to appear normally! Thanks again!
