### ISSUE TITLE
Error: Running LUA method 'loadSharedI3DFileFinished'.

### ISSUE THREAD

**Issue by lookee86** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#73]
I cant open RVB menu. In log I have error:
Error: Running LUA method 'loadSharedI3DFileFinished'.
N:/FS/FS22mods/FS22_Real_Vehicle_Breakdowns/scripts/gui/RVBGeneralSettings_Frame.lua:45: attempt to index field 'difficultySet' (a nil value)

RVB v 0.8.8.0

**Comment by MathiasHun** [comment]
I assume you downloaded this?
https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA.git
I fixed it from the phone. The Github version may have bugs, I made it at night and didn't check the Github version.

I checked this 
https://sharemods.com/ux7ykntyjof7/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html

**Comment by lookee86** [comment]
Ok. Now it works.
