### ISSUE TITLE
Used vehicle issue

### ISSUE THREAD

**Issue by MX5Marc** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#74]
Hi,

I had to stop using this mod a while back due to every vehicle I purchased at the store in the sale items needing repair and not being able to start them.  Does this still happen or is that something that can be fixed?  I'd love to start using it again.

Thanks

**Comment by MathiasHun** [comment]
Feel free to try it, it shouldn't be a problem anymore
