### ISSUE TITLE
Battery issue

### ISSUE THREAD

**Issue by AngryWexican** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#75]
Hey Mathias, first of all, great mod.

There seems to be an issue when the battery dies. there is no response from anything and the game goes very laggy. I've loaded up the mod on its own and it seems to still have this issue so isn't a conflict issue from what i gather.

Kind Regards

TheAngryWexican

**Comment by MathiasHun** [comment]
Fixed

**Comment by AngryWexican** [comment]
Legend of a man, i'll redownload it and check it out. Keep up the great work
