### ISSUE TITLE
Cant repair

### ISSUE THREAD

**Issue by lookee86** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#76]
Hi. 

I have another issue.
Inspection in damaged vehicle didnt found any damage(for exapmle tractor damaged in 60%). So I cant repair this vehicle. Time to inspection is far and there is any way to repair. My tractor after drive out from workshop still have 60% damage.

**Comment by MathiasHun** [comment]
If the damage bar of the vehicle is <=10 %
In this case, if no fault is found, the vehicle's damage bar is set to 100%.

If it finds a bug, it fixes the bug and restores the vehicle's damage bar in a random %.
