### ISSUE TITLE
Battery empty but charged

### ISSUE THREAD

**Issue by 0scarZulu** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#77]
![image](https://github.com/user-attachments/assets/e95991ed-6014-4f57-b336-2eca43f15e2c)
![image](https://github.com/user-attachments/assets/0c799c5b-69e2-45f5-a9c2-4e08c61b653d)

The tractor says the battery is empty but in the overview it is still 25% charged.

**Comment by MathiasHun** [comment]
According to my knowledge, 25% is not enough to start the vehicle, that is why it does not start.

**Comment by 0scarZulu** [comment]
25%? So with a quarter charged battery I can still get quite a way with my car. At less than 5%, I would understand that there are problems when starting and at 1-2% there may be a risk of deep discharging. But at 25%? Sorry, but I think that's too much.

**Comment by MathiasHun** [comment]
The vehicles got batteries, so I rewrote a lot of things. Battery charge level < 10%, the engine does not start.
