### ISSUE TITLE
Displaying the remaining time

### ISSUE THREAD

**Issue by 0scarZulu** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#80]
![image](https://github.com/user-attachments/assets/d79a6187-32ab-49cf-b030-0bb1ebc5f32f)

Hello, me again :) 

It would also be very cool if, for example, the information at the bottom that the repair is in progress showed how long it will take. 
Or something like "The repair will be completed in x hours and x minutes". Or again somewhere the info what it is completed. Today / time or tomorrow / time.

Cheers
Oz

**Comment by MathiasHun** [comment]
It's ready, just not uploaded. Thank you for your comment.
