### ISSUE TITLE
Battery dead (15%) after alt tabbing 

### ISSUE THREAD

**Issue by LonelyHowl** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#81]
Tractor: Fendt 1050
Had lights and front high beam on without the engine running when I alt tabbed for less than 5 minutes.
When I came back to the game, the battery was 15%, so the engine couldn't start.
In game only ~40 minutes had passed so I thought this was weird.
I used another mod, Towing Chain, to tow it to the workshop. Unfortunately it didn't show me an option to charge the battery (which it did before with another vehicle)

(Feature suggestion  would be something like a kickstarter or connecting another tractor to kickstart the broken down vehicle)

**Comment by MathiasHun** [comment]
The vehicles got batteries, so I rewrote a lot of things.

For example, it will be possible to charge the vehicle's battery with the JCB E-tech Powerpack mod.
