### ISSUE TITLE
Is it only possible to charge the battery with the Powerpack now?

### ISSUE THREAD

**Issue by danyelvl** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#84]
Before, it was possible to charge the battery through the menu. I saw that you were asked to use the powerpack to recharge, but now it will only be possible with it? I would still like to be able to load directly from the menu, or some way to start it with another vehicle nearby, who knows.

**Comment by MathiasHun** [comment]
Powerpack and charging stations.

Hmm, menu? I'll think about it.
