### ISSUE TITLE
Battery empty with AD

### ISSUE THREAD

**Issue by OGW-LBO** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#85]
When I use the AutoDrive helper and it gets blocked. If you notice this too late, the battery is empty.

VG

**Comment by DNeo** [comment]
Yep, we have that almost every day. That's why we don't pay the drivers

**Comment by DrewCZ** [comment]
in our case, the vehicle is stucked, but still with running engine. then when task is canceled for unblock, battery is empty. make no sense for me, sorry.
