### ISSUE TITLE
We love your mod but have 1 suggested changes.

### ISSUE THREAD

**Issue by DNeo** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#86]
We love your mod. It has added a lot of extra fun to the game and there is a use for the tow trucks from 82Studio. We had to build our own towing yard with a workshop to keep everything running permanently. At this point the mod has turned off our entire fleet.
![Skjermbilde 2024-08-15 131156](https://github.com/user-attachments/assets/28b35f28-d295-4990-b7f2-509e22ba1dfd)

We would like to suggest one changes.

2. Settings for how often something breaks as an admin in the game.

**Comment by MathiasHun** [comment]
I designed these settings for the release version.
