### ISSUE TITLE
Lime spreaders stuck at 6mph

### ISSUE THREAD

**Issue by BusinessWoofer** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#88]
I found out that certain lime spreaders such as the modded Stara Hercules 6.0 from Kingmods, or the Oxbo manure spreaders from the  Oxbo DLC. are stuck at a working speed of 6mph. Their working speed should be 18mph for the Stara as example. I have tested this by removing every mod and leave the RVB active and sure enough its RVB causing the working speed to be stuck at 6 MPH.

**Comment by MathiasHun** [comment]
I think I fixed this already.
Reported here issues https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/issues/55

[Download the latest developer version](https://sharemods.com/tq3yqqb6pmxb/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html)

**Comment by BusinessWoofer** [comment]
oh okay, thank you
