### ISSUE TITLE
Engine start temperature

### ISSUE THREAD

**Issue by DrewCZ** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#89]
Hey Mathias, please consider that if possible to set the start engine temperature according to the environment temperature. Because start at i.e. 21°C is more realistic and will be better than 1°C in mid summer :)
thank you, love your mod!
drewCZ aka ticho

**Comment by MathiasHun** [comment]
Currently taking as well into account.
current temperature - 15 = starting motor temperature
starting motor temperature >= 0

For example, if the temperature is 30 degrees, the engine starts at 15 degrees.

But like everything else, this can still be changed.
