### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Drmattymd** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#9]
I noticed a couple of small issues with the English translations in the warning messages. I have corrected them and would gladly share them with you if you would like that file.

**Comment by MathiasHun** [comment]
Hi, thank you for your comment and you can send it

**Comment by Drmattymd** [comment]
Ok, whats the best way to send it? I tried to add it to the code page but it said needed push authorization or something like that. Email maybe?

**Comment by MathiasHun** [comment]
Feel free to copy it here

**Comment by Drmattymd** [comment]
Not sure why I didnt think of that.. haha

**Comment by MathiasHun** [comment]
You are trying to use "Code"
![code](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/30857803/a6c5f17d-5a7b-4da7-852b-3c0324df5932)

**Comment by Hilbert1982** [comment]
below is the dutch translation : `l10n_nl.xml`

<?xml version="1.0" encoding="UTF-8"?>
<l10n>
	<texts>
		
		<text name="input_VEHICLE_BREAKDOWN_MENU" text="Echte voertuigpech(RVB)"/>

		
		
		<text name="ui_RVB_reset_msg" text="Weet je het zeker?"/>
		
		<text name="ui_RVB_sectionGamePlaySettings" text="Spelinstellingen"/>
		<text name="ui_RVB_gameplaysetting_dailyOperatingTimeTitle" text="Dagelijkse dienst"/>
		<text name="ui_RVB_gameplaysetting_dailyOperatingTimeDesc" text="Hoe vaak moet er onderhoud worden uitgevoerd per dag. Deze functie is momenteel inactief."/>
		<text name="ui_RVB_gameplaysetting_periodicOperatingTimeTitle" text="Periodische dienst"/>
		<text name="ui_RVB_gameplaysetting_periodicOperatingTimeDesc" text="Voertuigonderhoudsinterval."/>
		<text name="ui_RVB_gameplaysetting_repaironlyTitle" text="Reparatie alleen in voertuigwerkplaats"/>
		<text name="ui_RVB_gameplaysetting_repaironlyDesc" text="Een voertuig kan alleen worden gerepareerd of onderhouden in een voertuigwerkplaats."/>
		<text name="ui_RVB_gameplaysetting_workshopOpenTitle" text="Opening voertuigwerkplaats"/>
		<text name="ui_RVB_gameplaysetting_workshopOpenDesc" text="De voertuigwerkplaats gaat dan open"/>
		<text name="ui_RVB_gameplaysetting_workshopCloseTitle" text="Voertuigwerkplaats sluit"/>
		<text name="ui_RVB_gameplaysetting_workshopCloseDesc" text="De voertuigwerkplaats sluit op dat moment"/>
		
		<text name="ui_RVB_sectionGeneralSettings" text="Algemene instellingen"/>
		<text name="ui_RVB_generalsetting_alertMessageTitle" text="Waarschuwingsbericht"/>
		<text name="ui_RVB_generalsetting_alertMessageDesc" text="Als uw voertuig beschadigd, onderhouden of gerepareerd is, verschijnt er een waarschuwingsbericht in het midden van het scherm als u zich in het voertuig bevindt."/>

		
		<text name="RVB_WorkShopClose" text="Voertuigwerkplaats is gesloten, kom terug om %s uur." tag="format"/>
		<text name="RVB_button_inspection" text="Inspectie"/>
		<text name="RVB_button_dailyservice" text="Dagelijkse service"/>
		<text name="RVB_button_periodicservice" text="Periodieke service"/>
		<text name="RVB_button_battery_ch" text="Batterij wordt opgeladen"/>
		<text name="RVB_button_service" text="Service"/>
		<text name="RVB_button_vehicles" text="Voertuigen"/>
		<text name="RVB_button_vehiclesandequipment" text="Voertuigen en werktuigen"/>
		<text name="RVB_inspectionDialog" text="Weet u zeker dat u dit voertuig kunt inspecteren voor %s kosten?" tag="format"/>
		<text name="RVB_inspectionTimeDialog" text="Voertuiginspectie zal voltooid zijn om %s." tag="format"/>
		<text name="RVB_inspectionDayDialog" text="De voertuiginspectie wordt morgen om %s voltooid." tag="format"/>
		<text name="RVB_faultText_thermostatoverHeating" text="Thermostaat word te warm"/>
		<text name="RVB_faultText_thermostaatoverkoeling" text="Thermostaat blijft koud"/>
		<text name="RVB_faultText_lightings" text="Verlichting"/>
		<text name="RVB_faultText_glow_plug" text="Gloeispiraal"/>
		<text name="RVB_faultText_wipers" text="Ruitenwissers"/>
		<text name="RVB_faultText_generator" text="Dynamo"/>
		<text name="RVB_faultText_engine" text="Motor"/>
		<text name="RVB_faultText_self_starter" text="Zelfstarter"/>
		<text name="RVB_faultText_batteryisDead" text="Batterij"/>
		<text name="RVB_repairTimeDialog" text="De reparatie van het voertuig zal voltooid zijn om %s." tag="format"/>
		<text name="RVB_repairDayDialog" text="De reparatie van het voertuig wordt morgen om %s voltooid." tag="format"/>
		<text name="RVB_ErrorList" text="Foutenlijst:"/>
		<text name="RVB_periodicserviceDialog" text="Weet u zeker dat u het voertuig wilt laten onderhouden voor %s kosten?" tag="format"/>
		<text name="RVB_periodicserviceTimeDialog" text="Het voertuigonderhoud zal voltooid zijn om %s." tag="format"/>
		<text name="RVB_periodicserviceDayDialog" text="Het voertuigonderhoud zal morgen om %s voltooid zijn." tag="format"/>
		<text name="RVB_batteryChDialog" text="Weet u zeker dat u de accu van uw voertuig wilt opladen voor %s kosten?" tag="format"/>
		<text name="RVB_batteryChTimeDialog" text="Het opladen van de accu van het voertuig zal voltooid zijn om %s." tag="format"/>
		<text name="RVB_batteryChDayDialog" text="Het opladen van de accu van het voertuig zal morgen om %s voltooid zijn." tag="format"/>
		<text name="RVB_occupied" text="Voertuig is al in gebruik!"/>
		<text name="RVB_shop_operatingTime" text="%02d.%2d uur" tag="format"/>
		<text name="RVB_serviceHours" text="%01d/%01d uur" tag="format"/>
		<text name="RVB_alertmessage_inspection" text="Voertuiginspectie is bezig."/>
		<text name="RVB_alertmessage_inspection_hud" text="%s voertuiginspectie is bezig."/>
		<text name="RVB_alertmessage_repair" text="Het voertuig wordt gerepareerd."/>
		<text name="RVB_alertmessage_repair_hud" text="%s voertuig wordt gerepareerd."/>
		<text name="RVB_alertmessage_service" text="Het voertuigonderhoud wordt uitgevoerd."/>
		<text name="RVB_alertmessage_service_hud" text="%s voertuigonderhoud is bezig."/>
		<text name="RVB_alertmessage_batteryCh" text="Batterij wordt opgeladen."/>
		<text name="RVB_alertmessage_batteryCh_hud" text="%s voertuigaccu wordt opgeladen."/>
		
		<text name="RVB_list_vehicleorimplement" text="Voertuigen/werktuigen"/>
		<text name="RVB_list_hporle" text="Hp/LE"/>
		<text name="RVB_list_currentvalue" text="Huidige prijs"/>
		<text name="RVB_list_age" text="Leeftijd"/>
		<text name="RVB_list_operatinghours" text="Bedrijfstijd"/>
		<text name="RVB_list_realoperatinghours" text="Echte bedrijfstijd"/>
		<text name="RVB_list_servicehours" text="Service"/>
		<text name="RVB_list_lease" text="Verhuurd"/>
		<text name="RVB_list_battery" text="Batterij"/>


		
		<text name="RVB_inspectionDialogFault" text="%s voertuig geïnspecteerd, reparatie vereist. %s"/>
		<text name="RVB_inspectionDialogEnd" text="%s voertuig geïnspecteerd, geen reparaties vereist."/>


		<text name="RVB_fault_" text="Rijd niet te snel, de motor is nog koud."/>
		<text name="RVB_fault_hud" text="%s het voertuig rijdt te snel, de motor is nog koud." tag="format"/>

		<text name="RVB_fault_thermostaat" text="Koelvloeistof raakt oververhit."/>
		<text name="RVB_fault_thermostat_hud" text="%s voertuigkoelvloeistof raakt oververhit." tag="format"/>

		<text name="RVB_fault_thermostatC" text="De motor bereikt de bedrijfstemperatuur niet."/>
		<text name="RVB_fault_thermostatC_hud" text="%s motor bereikt de bedrijfstemperatuur niet." tag="format"/>

		<text name="RVB_fault_lights" text="De verlichting werkt niet."/>
		<text name="RVB_fault_lights_hud" text="%s de verlichting van het voertuig werkt niet." tag="format"/>

		<text name="RVB_fault_glowplug" text="Brandstofverbruik is toegenomen."/>
		<text name="RVB_fault_glowplug_hud" text="%s brandstofverbruik van voertuig verhoogd." tag="format"/>

		<text name="fault_battery" text="Batterij loopt leeg."/>
		<text name="fault_battery_hud" text="%s de accu van het voertuig is leeg." tag="format"/>

		<text name="RVB_fault_operatinghours" text="Het servicelampje ging branden."/>
		<text name="RVB_fault_operatinghours_hud" text="%s voertuig heeft onderhoud nodig." tag="format"/>


		<text name="RVB_main_repair_fault" text="De monteur kan dit voertuig niet repareren, ga naar &quot;RVB&quot; Service."/>


		<text name="popupMessage_battery_timeScaleup" text="Mechanic: Schakel de batterijlader niet aan en uit, omdat het opladen dan langer duurt."/>
		<text name="popupMessage_battery_timeScaledown" text="Monteur: laat de oplader met rust."/>

		
		
		<text name="VehicleBreakdown_DEAD_ENGINE" text="Motorstoring."/>
		<text name="VehicleBreakdown_DEAD_GENERATOR" text="De motor start niet, de generator is defect."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_INSPECTION" text="Voertuig kan niet worden gestart, de inspectie is bezig."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_REPAIR" text="Voertuig kan niet worden gestart, reparatie wordt uitgevoerd."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_SERVICE" text="Het voertuig kan niet worden gestart, er wordt onderhoud uitgevoerd."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_SUSPENSION" text="De voertuigsleutel ligt bij de monteur, die momenteel rust."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_BATTERY" text="Motor start niet, accu is leeg."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_BATTERY_CHARGING" text="Voertuig kan niet worden gestart, de batterij wordt opgeladen."/>




		<text name="infoDisplayExtension_tomorrow" text="morgen "/>
		<text name="infoDisplayExtension_currentPower" text="Power"/>
		<text name="infoDisplayExtension_batteryCh" text="Batterij wordt opgeladen"/>
		<text name="infoDisplayExtension_inspectionVheicle" text="Voertuiginspectie"/>
		<text name="infoDisplayExtension_repairVheicle" text="Voertuigreparatie"/>

		<text name="infoDisplayExtension_serviceVheicle" text="Periodieke service"/>

		<text name="RVB_operatingHours" text="Service-uren"/>

		<text name="RVB_TotaloperatingHours" text="Totaal bedrijfsuren"/>





		<text name="warning_multiplayerNotDetected" text="Een '%s'-modus....."/>


		</texts>




</l10n>

**Comment by RoberT162v** [comment]
Hello, this would be the Spanish translation. All the best. 
<l10n>
	<texts>
		
		<text name="input_VEHICLE_BREAKDOWN_MENU" text="Real Vehicle Breakdowns(RVB)"/>

		
		
		<text name="ui_RVB_reset_msg" text="Estas seguro?"/>
		
		<text name="ui_RVB_sectionGamePlaySettings" text="Configuraciones de juego"/>
		<text name="ui_RVB_gameplaysetting_dailyOperatingTimeTitle" text="Servicio diario"/>
		<text name="ui_RVB_gameplaysetting_dailyOperatingTimeDesc" text="¿Con qué frecuencia se debe realizar el mantenimiento al día? Esta característica está actualmente inactiva."/>
		<text name="ui_RVB_gameplaysetting_periodicOperatingTimeTitle" text="Servicio periódico"/>
		<text name="ui_RVB_gameplaysetting_periodicOperatingTimeDesc" text="Intervalo de servicio del vehículo."/>	
		<text name="ui_RVB_gameplaysetting_repaironlyTitle" text="Reparación sólo en taller de vehículos."/>
		<text name="ui_RVB_gameplaysetting_repaironlyDesc" text="Un vehículo sólo puede repararse o recibir servicio en un taller de vehículos."/>
		<text name="ui_RVB_gameplaysetting_workshopOpenTitle" text="Apertura del taller de vehículos"/>
		<text name="ui_RVB_gameplaysetting_workshopOpenDesc" text="Hora de apertura del taller de vehículos."/>
		<text name="ui_RVB_gameplaysetting_workshopCloseTitle" text="Cierre del taller de vehículos"/>
		<text name="ui_RVB_gameplaysetting_workshopCloseDesc" text="Hora de cierre del taller de vehículos."/>
		
		<text name="ui_RVB_sectionGeneralSettings" text="Configuración general"/>
		<text name="ui_RVB_generalsetting_alertMessageTitle" text="Mensaje de alerta"/>
		<text name="ui_RVB_generalsetting_alertMessageDesc" text="Si su vehículo sufre daños, se le da servicio o se repara, aparecerá un mensaje de advertencia en el medio de la pantalla si se encuentra en el vehículo."/>
		<text name="ui_RVB_generalsetting_difficultyTitle" text="Averías del vehículo"/>
		<text name="ui_RVB_generalsetting_difficultyDesc" text="Está en desarrollo pero listo para usar."/>
		<text name="ui_RVB_difficulty1_subtitle" text="Lenta"/>
		<text name="ui_RVB_difficulty2_subtitle" text="Media"/>
		<text name="ui_RVB_difficulty3_subtitle" text="Rápida"/>

			
		<text name="RVB_WorkShopClose" text="El taller de vehículos está cerrado, vuelva a las %s." tag="format"/>
		<text name="RVB_button_inspection" text="Inspección"/>
		<text name="RVB_button_dailyservice" text="Servicio diario"/>
		<text name="RVB_button_periodicservice" text="Servicio periódico"/>
		<text name="RVB_button_battery_ch" text="Cargando batería"/>
		<text name="RVB_button_service" text="Servicio"/>
		<text name="RVB_button_vehicles" text="Vehiculos"/>
		<text name="RVB_button_vehiclesandequipment" text="Vehiculos e implementos"/>
		<text name="RVB_inspectionDialog" text="¿Estás seguro de que quieres inspeccionar este vehículo por un coste de %s?" tag="format"/>
		<text name="RVB_inspectionTimeDialog" text="La inspección del vehículo se completará a las %s." tag="format"/>
		<text name="RVB_inspectionDayDialog" text="La inspección del vehículo finalizará mañana a las %s." tag="format"/>
		<text name="RVB_faultText_THERMOSTAT" text="Termostato"/>
		<text name="RVB_faultText_LIGHTINGS" text="iluminación"/>
		<text name="RVB_faultText_GLOWPLUG" text="Bujía incandescente"/>
		<text name="RVB_faultText_WIPERS" text="Limpia parabrisas"/>
		<text name="RVB_faultText_GENERATOR" text="Alternador"/>
		<text name="RVB_faultText_ENGINE" text="Motor"/>
		<text name="RVB_faultText_SELFSTARTER" text="Motor de arranque"/> 
		<text name="RVB_faultText_BATTERY" text="Bateria"/>
		<text name="RVB_repairTimeDialog" text="La reparación del vehículo se completará en %s." tag="format"/>
		<text name="RVB_repairDayDialog" text="La reparación del vehículo finalizará mañana a las %s." tag="format"/>
		<text name="RVB_ErrorList" text="Lista de errores:" />
		<text name="RVB_periodicserviceDialog" text="¿Está seguro de que desea reparar el vehículo por un coste de %s?" tag="format"/>
		<text name="RVB_periodicserviceTimeDialog" text="El servicio del vehículo se completará en %s." tag="format"/>
		<text name="RVB_periodicserviceDayDialog" text="El servicio del vehículo finalizará mañana a las %s." tag="format"/>
		<text name="RVB_batteryChDialog" text="¿Estás seguro de que deseas cargar la batería de tu vehículo por %s de coste?" tag="format"/>
		<text name="RVB_batteryChTimeDialog" text="La carga de la batería del vehículo se completará a las %s." tag="format"/>
		<text name="RVB_batteryChDayDialog" text="La carga de la batería del vehículo finalizará mañana a las %s." tag="format"/>
		<text name="RVB_occupied" text="¡El vehículo ya está en uso!" />
		<text name="RVB_shop_operatingTime" text="%02d.%2d Hora" tag="format"/>
		<text name="RVB_serviceHours" text="%01d/%01d Hora" tag="format"/>
		<text name="RVB_alertmessage_inspection" text="La inspección del vehículo está en curso."/>
		<text name="RVB_alertmessage_inspection_hud" text="%s La inspección del vehículo está en curso." tag="format"/>
		<text name="RVB_alertmessage_repair" text="La reparación del vehículo está en curso."/>
		<text name="RVB_alertmessage_repair_hud" text="%s vehículos reparados están en progreso." tag="format"/>
		<text name="RVB_alertmessage_service" text="El servicio del vehículo está en curso."/>
		<text name="RVB_alertmessage_service_hud" text="%s vehículo reparado está en progreso." tag="format"/>
		<text name="RVB_alertmessage_batteryCh" text="La carga de la batería está en curso."/>
		<text name="RVB_alertmessage_batteryCh_hud" text="La carga de la batería del vehículo de %s está en curso." tag="format"/>
		
		<text name="RVB_list_vehicleorimplement" text="Vehículos/Implementos"/>
		<text name="RVB_list_hporle" text="CV/LE"/>
		<text name="RVB_list_currentvalue" text="Precio actual"/>
		<text name="RVB_list_age" text="Edad"/>
		<text name="RVB_list_operatinghours" text="Horas de funcionamiento"/>
		<text name="RVB_list_realoperatinghours" text="Horas reales de funcionamiento"/>
		<text name="RVB_list_servicehours" text="Servicio"/>
		<text name="RVB_list_lease" text="Alquilado"/>
		<text name="RVB_list_battery" text="Bateria"/>
		<text name="RVB_parts_repair" text="Piezas a reparar"/>

		
		<text name="RVB_inspectionDialogFault" text="%s vehículo inspeccionado, se requieren reparaciones. %s"/>
		<text name="RVB_inspectionDialogEnd" text="%s vehículo inspeccionado, no se requieren reparaciones."/>
		<text name="RVB_inspectionDialogEnd_other" text="%s vehículo ha sido inspeccionado y reparado. Su mecánico tenía mucho trabajo, por lo que un mecánico novato arregló su vehículo. Sin embargo, este mecánico novato no puede enumerar lo que ha reparado en su vehículo."/>
		
		<text name="RVB_fault_" text="No conduzca demasiado rápido, el motor todavía está frío."/>
		<text name="RVB_fault_hud" text="%s el vehículo se conduce demasiado rápido y el motor aún está frío." tag="format"/>

		<text name="RVB_fault_thermostat" text="El refrigerante se sobrecalienta."/>
		<text name="RVB_fault_thermostat_hud" text="%es el refrigerante del vehículo se sobrecalienta." tag="format"/>

		<text name="RVB_fault_thermostatC" text="El motor no alcanza la temperatura de funcionamiento."/>
		<text name="RVB_fault_thermostatC_hud" text="%s motor no alcanza la temperatura de funcionamiento." tag="format"/>

		<text name="RVB_fault_lights" text="La iluminación no funciona." />
		<text name="RVB_fault_lights_hud" text="Las luces del vehículo de %s no funcionan." tag="format"/>

		<text name="RVB_fault_glowplug" text="El consumo de combustible ha aumentado." />
		<text name="RVB_fault_glowplug_hud" text="%s el consumo de combustible del vehículo aumentó." tag="format"/>

		<text name="fault_battery" text="La batería se descarga." />
		<text name="fault_battery_hud" text="La batería de un vehículo %s está descargada." tag="format"/>

		<text name="RVB_fault_operatinghours" text="Se encendió la luz de servicio." />
		<text name="RVB_fault_operatinghours_hud" text="%s vehículo necesita servicio." tag="format"/>

		<text name="RVB_main_repair_fault" text="El mecánico no puede reparar este vehículo, visite &quot;RVB&quot; Servicio."/>

		<text name="VehicleBreakdown_DEAD_ENGINE" text="Fallo del motor."/>
		<text name="VehicleBreakdown_DEAD_GENERATOR" text="El motor no arranca, el alternador ha fallado."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_INSPECTION" text="El vehículo no se puede arrancar, la inspección está en curso."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_REPAIR" text="El vehículo no se puede arrancar, la reparación está en curso."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_SERVICE" text="El vehículo no se puede arrancar, se está realizando el servicio."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_SUSPENSION" text="La llave del vehículo está en manos del mecánico, quien actualmente se encuentra en reposo."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_BATTERY" text="El motor no arranca, la batería está agotada."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_BATTERY_CHARGING" text="El vehículo no se puede arrancar, la batería está cargando."/>

		<text name="RVB_ErrorNotifi" text="Avería(s): "/>

		
		<text name="infoDisplayExtension_tomorrow" text="Mañana "/>
		<text name="infoDisplayExtension_currentPower" text="Potencia"/>
		<text name="infoDisplayExtension_batteryCh" text="Cargando batería"/>
		<text name="infoDisplayExtension_inspectionVheicle" text="Inspeccion de vehiculo"/>
		<text name="infoDisplayExtension_repairVheicle" text="Reparación de vehículos"/>
		<text name="infoDisplayExtension_serviceVheicle" text="Servicio periódico"/>

		<text name="RVB_operatingHours" text="Horas de servicio"/>

		<text name="RVB_TotaloperatingHours" text="Horas totales de servicio"/>

		
		<text name="Automatic_Repair_conflict_notice" text="Hay modificaciones que reparan automáticamente el vehículo, pero puedes utilizar la función &quot;Averías reales del vehículo(RVB)&quot;. también está utilizando una modificación, por lo que puede entrar en conflicto con otras modificaciones. En las modificaciones en la lista a continuación, es necesario anular la reparación automática, esta anulación ya fue realizada por la modificación RVB."/>
		<text name="Automatic_Repair_conflict_list" text="&#13;&#10;Modificaciones sobrescritas:"/>
		<text name="Automatic_Repair_conflict_signature" text="&#13;&#10;Gracias por su comprensión.&#13;&#10;&#13;&#10;Saludos,&#13;&#10;MathiasHun"/>

	</texts>
</l10n>

**Comment by MathiasHun** [comment]
You didn't translate the following two lines. Thanks.
```

<text name="RVB_fault_" text="Do not drive too fast, the engine is still cold."/>
<text name="RVB_fault_hud" text="%s the vehicle is driven too fast, the engine is still cold." tag="format"/>
```

**Comment by RoberT162v** [comment]
I have edited the previous message and they are already translated.
beginner mistake hehe

**Comment by MathiasHun** [comment]
I make mistake too

**Comment by DoxoMatixo** [comment]
Updated Turkish translation.

<?xml version="1.0" encoding="UTF-8"?>
<l10n>
	<texts>
		
		<text name="input_VEHICLE_BREAKDOWN_MENU" text="Gerçek Araç Arızaları(GAA)"/>

		
		
		<text name="ui_RVB_reset_msg" text="Emin misiniz?"/>
		
		<text name="ui_RVB_sectionGamePlaySettings" text="Oyun Ayarları"/>
		<text name="ui_RVB_gameplaysetting_dailyOperatingTimeTitle" text="Günlük hizmet"/>
		<text name="ui_RVB_gameplaysetting_dailyOperatingTimeDesc" text="Bakım günde ne sıklıkla yapılmalı? Bu özellik şu anda aktif değil."/>
		<text name="ui_RVB_gameplaysetting_periodicOperatingTimeTitle" text="Periyodik bakım"/>
		<text name="ui_RVB_gameplaysetting_periodicOperatingTimeDesc" text="Araç bakım aralığı."/>	
		<text name="ui_RVB_gameplaysetting_repaironlyTitle" text="Sadece araç tamirhanesinde tamir edin."/>
		<text name="ui_RVB_gameplaysetting_repaironlyDesc" text="Bir araç sadece araç tamirhanesinde tamir edilebilir veya bakımı yapılabilir."/>
		<text name="ui_RVB_gameplaysetting_workshopOpenTitle" text="Araç tamirhanesi açılış saati"/>
		<text name="ui_RVB_gameplaysetting_workshopOpenDesc" text="Araç tamirhanesin açılış saati. Sadece ayarladığınız saatte açılır."/>
		<text name="ui_RVB_gameplaysetting_workshopCloseTitle" text="Araç tamirhanesi kapanı saati."/>
		<text name="ui_RVB_gameplaysetting_workshopCloseDesc" text="Araç tamirhanesin kapanış saati. Sadece ayarladığınız saatte kapanır."/>
		
		<text name="ui_RVB_sectionGeneralSettings" text="Genel Ayarlar"/>
		<text name="ui_RVB_generalsetting_alertMessageTitle" text="Uyarı mesajı"/>
		<text name="ui_RVB_generalsetting_alertMessageDesc" text="Araç hasar gördüğünde, servise götürüldüğünde veya tamir edildiğinde araç içindeyseniz ekranın ortasında bir uyarı mesajı görünecektir."/>
		<text name="ui_RVB_generalsetting_difficultyTitle" text="Araç arızası"/>
		<text name="ui_RVB_generalsetting_difficultyDesc" text="Geliştirme aşamasında ama kullanıma hazır."/>
		<text name="ui_RVB_difficulty1_subtitle" text="Yavaş"/>
		<text name="ui_RVB_difficulty2_subtitle" text="Orta"/>
		<text name="ui_RVB_difficulty3_subtitle" text="Hızlı"/>

			
		<text name="RVB_WorkShopClose" text="Araç tamirhanesi kapalı, Saat %s geri gelin." tag="format"/>
		<text name="RVB_button_inspection" text="İnceleme"/>
		<text name="RVB_button_dailyservice" text="DGünlük servis"/>
		<text name="RVB_button_periodicservice" text="Periyodik bakım"/>
		<text name="RVB_button_battery_ch" text="Akü şarjı"/>
		<text name="RVB_button_service" text="Bakım"/>
		<text name="RVB_button_vehicles" text="Araçlar"/>
		<text name="RVB_button_vehiclesandequipment" text="Araçlar ve uygulamalar"/>
		<text name="RVB_inspectionDialog" text="Bu aracı %s maliyetle incelemek istediğine emin misin?" tag="format"/>
		<text name="RVB_inspectionTimeDialog" text="Araç incelemesi %s saatinde tamamlanacaktır." tag="format"/>
		<text name="RVB_inspectionDayDialog" text="Araç incelemesi yarın %s saatinde tamamlanacak." tag="format"/>
		<text name="RVB_faultText_THERMOSTAT" text="Termostat"/>
		<text name="RVB_faultText_LIGHTINGS" text="Aydınlatma"/>
		<text name="RVB_faultText_GLOWPLUG" text="Buji"/>
		<text name="RVB_faultText_WIPERS" text="Silecekler"/>
		<text name="RVB_faultText_GENERATOR" text="Şarj Dinamosu"/>
		<text name="RVB_faultText_ENGINE" text="Motor"/>
		<text name="RVB_faultText_SELFSTARTER" text="Marş Dinamosu"/> 
		<text name="RVB_faultText_BATTERY" text="Akü"/>
		<text name="RVB_repairTimeDialog" text="Araç tamiri %s saatinde tamamlanacak." tag="format"/>
		<text name="RVB_repairDayDialog" text="Araç tamiri yarın saat %s'te tamamlanacak." tag="format"/>
		<text name="RVB_ErrorList" text="Hata listesi:" />
		<text name="RVB_periodicserviceDialog" text="%s maliyetle aracı servise bırakmak istediğinizden emin misiniz?" tag="format"/>
		<text name="RVB_periodicserviceTimeDialog" text="Araç servisi %s saatinde tamamlanacak." tag="format"/>
		<text name="RVB_periodicserviceDayDialog" text="Araç servisi yarın %s saatinde tamamlanacak." tag="format"/>
		<text name="RVB_batteryChDialog" text="%s maliyetle araç aküsünü şarj etmek istediğinizden emin misiniz?" tag="format"/>
		<text name="RVB_batteryChTimeDialog" text="Araç akü şarjı %s saatinde tamamlanacak." tag="format"/>
		<text name="RVB_batteryChDayDialog" text="Araç akü şarjı yarın %s saatinde tamamlanacak." tag="format"/>
		<text name="RVB_occupied" text="Araç zaten kullanımda!" />
		<text name="RVB_shop_operatingTime" text="%02d.%2d saat" tag="format"/>
		<text name="RVB_serviceHours" text="%01d/%01d saat" tag="format"/>
		<text name="RVB_alertmessage_inspection" text="Araç incelemesi devam ediyor."/>
		<text name="RVB_alertmessage_inspection_hud" text="%s araç incelemesi devam ediyor." tag="format"/>
		<text name="RVB_alertmessage_repair" text="Araç tamiri devam ediyor."/>
		<text name="RVB_alertmessage_repair_hud" text="%s araç tamiri devam ediyor." tag="format"/>
		<text name="RVB_alertmessage_service" text="Araç servisi devam ediyor."/>
		<text name="RVB_alertmessage_service_hud" text="%s araç servisi devam ediyor." tag="format"/>
		<text name="RVB_alertmessage_batteryCh" text="Akü şarjı devam ediyor."/>
		<text name="RVB_alertmessage_batteryCh_hud" text="%s araç akü şarjı devam ediyor." tag="format"/>
		
		<text name="RVB_list_vehicleorimplement" text="Araçlar/Ekipmanlar"/>
		<text name="RVB_list_hporle" text="Hp/LE"/>
		<text name="RVB_list_currentvalue" text="Güncel fiyat"/>
		<text name="RVB_list_age" text="Yaş"/>
		<text name="RVB_list_operatinghours" text="Çalışma süresi"/>
		<text name="RVB_list_realoperatinghours" text="Gerçek Çalışma Süresi"/>
		<text name="RVB_list_servicehours" text="Servis"/>
		<text name="RVB_list_lease" text="Kiralandı"/>
		<text name="RVB_list_battery" text="Akü"/>
		<text name="RVB_parts_repair" text="Onarılacak parçalar"/>

		
		<text name="RVB_inspectionDialogFault" text="Araç %s incelendi, onarım gerekiyor. %s"/>
		<text name="RVB_inspectionDialogEnd" text="Araç %s incelendi, onarım gerektirmiyor."/>
		<text name="RVB_inspectionDialogEnd_other" text="%s araç incelendi ve tamir edildi. Tamircinizin çok işi olduğu için çırak aracınızı tamir etti. Ancak çırak ustası olmadan tamir ettiği şeyleri listeleyemez."/>
.
		<text name="RVB_fault_" text="Çok hızlı sürmeyin, motor hala soğuk."/>
		<text name="RVB_fault_hud" text="%s araç çok hızlı sürülüyor, motor hala soğuk." tag="format"/>

		<text name="RVB_fault_thermostat" text="Antifriz aşırı ısınıyor."/>
		<text name="RVB_fault_thermostat_hud" text="%s aracın antifrizi aşırı ısınıyor." tag="format"/>

		<text name="RVB_fault_thermostatC" text="Motor çalışma sıcaklığına ulaşmıyor."/>
		<text name="RVB_fault_thermostatC_hud" text="Motor %s çalışma sıcaklığına ulaşmıyor." tag="format"/>

		<text name="RVB_fault_lights" text="Aydınlatma çalışmıyor." />
		<text name="RVB_fault_lights_hud" text="Aracın ışıkları %s çalışmıyor." tag="format"/>

		<text name="RVB_fault_glowplug" text="Yakıt tüketimi arttı." />
		<text name="RVB_fault_glowplug_hud" text="Aracın yakıt tüketimi %s arttı." tag="format"/>

		<text name="fault_battery" text="Akü bitiyor." />
		<text name="fault_battery_hud" text="Aracının pili %s boşaldı." tag="format"/>

		<text name="RVB_fault_operatinghours" text="Servis ışığı yandı." />
		<text name="RVB_fault_operatinghours_hud" text="Aracının %s oranında servise ihtiyacı var." tag="format"/>

		<text name="RVB_main_repair_fault" text="Tamirci bu aracı tamir edemez, &quot;RVB&quot; servisine gidin."/>

		<text name="VehicleBreakdown_DEAD_ENGINE" text="Motor arızası."/>
		<text name="VehicleBreakdown_DEAD_GENERATOR" text="Motor çalışmıyor. Marş dinamosu arızalandı."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_INSPECTION" text="Araç çalıştırılamıyor, inceleme devam ediyor."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_REPAIR" text="Araç çalıştırılamıyor, tamirat devam ediyor."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_SERVICE" text="Araç çalıştırılamıyor, servis bakım işlemi devam ediyor."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_SUSPENSION" text="Araç anahtarı tamircide ve o şu anda meşgul."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_BATTERY" text="Motor çalışmıyor, akü tamamen bitti."/>
		<text name="VehicleBreakdown_DEAD_ENGINE_BATTERY_CHARGING" text="Araç çalıştırılamıyor, akü şarjı devam ediyor."/>

		<text name="RVB_ErrorNotifi" text="Arıza(lar): "/>

		
		<text name="infoDisplayExtension_tomorrow" text="Yarın "/>
		<text name="infoDisplayExtension_currentPower" text="Güç"/>
		<text name="infoDisplayExtension_batteryCh" text="Akü şarjı"/>
		<text name="infoDisplayExtension_inspectionVheicle" text="Araç muayenesi"/>
		<text name="infoDisplayExtension_repairVheicle" text="Araç tamiri"/>
		<text name="infoDisplayExtension_serviceVheicle" text="Periyodik bakım"/>

		<text name="RVB_operatingHours" text="Servis saati"/>

		<text name="RVB_TotaloperatingHours" text="Toplam çalışma saati"/>

		
		<text name="Automatic_Repair_conflict_notice" text="Araçları otomatik olarak tamir eden modifikasyonlar var, ama siz &quot;Real Vehicle Breakdowns(RVB)&quot; kullanıyorsunuz, bu da diğer modifikasyonlarla çakışabilir. Aşağıdaki listedeki modifikasyon(lar) otomatik tamiri geçersiz kılmak gerekiyor, bu geçersiz kılma zaten RVB modifikasyonu tarafından yapıldı."/>
		<text name="Automatic_Repair_conflict_list" text="&#13;&#10;Üzerine yazılmış modifikasyon(lar): "/>
		<text name="Automatic_Repair_conflict_signature" text="&#13;&#10;Anlayışınız için teşekkür ederim.&#13;&#10;&#13;&#10;En iyi dileklerimle,&#13;&#10;MathiasHun"/>

	</texts>
</l10n>
