### ISSUE TITLE
error menu

### ISSUE THREAD

**Issue by Rippie08** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#90]
no vehicles showing up in the rvb menu, also with only rvb on elmcreek
![20240905132234_1](https://github.com/user-attachments/assets/157de97d-85a4-4429-b938-91f945980de0)

**Comment by MathiasHun** [comment]
issues https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/issues/12
> Have you got the setting on where toy cab only repair in Workshop. If so turn it off and you can see vehicles on the menu
