### ISSUE TITLE
Tractor not working due to unrepaired "Safety Weights Pack"?!!

### ISSUE THREAD

**Issue by vitalii2011** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#92]
https://www.farming-simulator.com/mod.php?mod_id=246581
![fsScreen_2024_09_18_17_51_24](https://github.com/user-attachments/assets/abacebe3-6065-40cd-95a6-e71ead9c2377)
[log.txt](https://github.com/user-attachments/files/17046009/log.txt)
It's not very clear.)

**Comment by MathiasHun** [comment]
I checked the RVB with the Safety Weights Pack. I’m not sure what the exact issue is on your end, but I definitely had a newer RVB version. It did cause some errors, which I fixed in version 0.9.0.0. Does the issue still exist after the update?

**Comment by vitalii2011** [comment]
There seem to be no problems now (in version 0.9.0.0).
Thank you.

**Comment by vitalii2011** [comment]
Is it possible to hide/move this very useful HUD?
![fsScreen_2024_11_04_11_05_39](https://github.com/user-attachments/assets/c75b3668-bda1-401a-a2c7-38c0a96b5635) 

P. S. 
And if possible, add lines to translate the names in this panel.

**Comment by MathiasHun** [comment]
The HUD hiding feature is ready. I will upload it soon. Language translation? Maybe that will be available too :)
