### ISSUE TITLE
just bugs out

### ISSUE THREAD

**Issue by retep1** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#94]
I don't no whats going on but after a well of playing and sleeping with trucks and thing running it will randomly start to bugout and it let me get into them but nothing else no starting no getting out nothing and slowly starts to happen to all of the vehicles only thing that fixes it is to get rid of your mod and it wont save any of the breakdown data like how long the vehicle bin running  please get back to me soon i love this mod

**Comment by MathiasHun** [comment]
[Download the latest developer version](https://sharemods.com/tq3yqqb6pmxb/FS22_gameplay_Real_Vehicle_Breakdowns.zip.html)

**Comment by retep1** [comment]
thank you
