### ISSUE TITLE
LUA Error 0.9.0.0

### ISSUE THREAD

**Issue by bojanh66** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#95]
2024-11-03 08:07 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
G:/FS22 mods/FS22_gameplay_Real_Vehicle_Breakdowns/scripts/vehicles/specializations/VehicleBreakdowns.lua:353: attempt to perform arithmetic on field 'lifetime' (a nil value)

Cant load savegame, stuck at 85% loading.
I have noticed that you dont have Releases, but you always upload latest version.
If its not a problem, make each Release separate download, like Courseplay guys, so we can download previous version in case the newest one is bugged, like now.
https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by MathiasHun** [comment]
Thank you for your bug report. I will upload the fix soon. Unfortunately, there was also a bug elsewhere, and it has been present since version 0.8.0.0. :) Since this is a beta version, I didn’t plan to share every version change.

**Comment by bojanh66** [comment]
The weird thing is, i can start new savegame with 0.9.0.0, but i cant load existing savegame with 0.9.0.0, it gets stuck at 85% loading, maybe this can help :)

**Comment by MathiasHun** [comment]
Hi, unfortunately, the 0.9.0.0 update wasn’t compatible with the old save, which I didn’t account for since it's a beta version. I'm uploading the fix now.
