### ISSUE TITLE
It is impossible to buy some vehicles

### ISSUE THREAD

**Issue by leo32128fs** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#98]
I tried to buy some sprayers and some fertilizer tanks and I couldn't find the vehicle itself, it doesn't even appear, an error was returned when trying to buy, version 0.9.0.1

C:/Users/leo32/Documents/My Games/FarmingSimulator2022/mods/FS22_gameplay_Real_Vehicle_Breakdowns/scripts/vehicles/specializations/VehicleBreakdowns.lua:3046: attempt to index local 'spec' (a nil value)

**Comment by MathiasHun** [comment]
Hi, thank you for the bug report! This part of the code hasn’t been updated in a long time, but it was indeed causing an error. I've fixed it, and I'll upload the update soon.

**Comment by leo32128fs** [comment]
> Olá, obrigado pelo relatório de bug! Esta parte do código não é atualizada há muito tempo, mas estava realmente causando um erro. Eu consertei e enviarei a atualização em breve.

OK thanks!

**Comment by MathiasHun** [comment]
Uploaded. If you do not experience the issue, please close the report.

**Comment by leo32128fs** [comment]
> Uploaded. If you do not experience the issue, please close the report.

Ok! Thanks, everything went well with this att, I'll close it now
